feat(layer): introducing web component
carbon-design-system/carbon-for-ibm-dotcom pull request #10213
Opened 2023-03-09 00:49 UTC by IgnacioBecerra

### Related Ticket(s)
#10197 

### Description
This PR creates the new Layer component that is being used in many component story variations of the v11 Storybook. This PR also adds CDN and CodeSandbox examples, as well as documentation.

### Changelog

**New**

- new `cds-layer` component

2023-03-13 14:54 UTC, kennylam commented
Minor thing but when going from `useLayer` back to `Default`, the component copy doesn't revert back.

![image](https://user-images.githubusercontent.com/909118/224739067-5a80ae60-5bc3-4e17-bc7c-9517f87b62dd.png)

2023-03-13 20:35 UTC, IgnacioBecerra commented
@RichKummer That's a Storybook reference, the wrapper styles should've been updated [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10211) to match with Carbon's SB styles.

@kennylam You're right, fixing this!

2023-03-14 13:19 UTC, kennylam requested changes
Looks good @IgnacioBecerra! Just some minor changes for the prefix.

2023-03-14 13:19 UTC, kennylam commented on packages/carbon-web-components/examples/codesandbox/basic/components/layer/cdn.html
> +    bx-button:not(:defined) {
```suggestion
    cds-button:not(:defined) {
```

2023-03-14 13:19 UTC, kennylam commented on packages/carbon-web-components/examples/codesandbox/basic/components/layer/index.html
> +    bx-button:not(:defined) {
```suggestion
    cds-button:not(:defined) {
```

2023-03-14 13:19 UTC, kennylam commented on packages/carbon-web-components/src/components/layer/layer.ts
> +class BXLayer extends LitElement {
```suggestion
class CDSLayer extends LitElement {
```

2023-03-14 13:19 UTC, kennylam commented on packages/carbon-web-components/src/components/layer/layer.ts
> +export default BXLayer;
```suggestion
export default CDSLayer;
```

2023-03-14 13:19 UTC, kennylam commented on packages/carbon-web-components/src/components/layer/layer.ts
> +        (this.constructor as typeof BXLayer).selectorLayer
```suggestion
        (this.constructor as typeof CDSLayer).selectorLayer
```

2023-03-14 13:19 UTC, kennylam commented on packages/carbon-web-components/src/components/layer/layer.ts
> +      new CustomEvent((this.constructor as typeof BXLayer).eventUseLayer, {
```suggestion
      new CustomEvent((this.constructor as typeof CDSLayer).eventUseLayer, {
```

2023-03-15 16:09 UTC, RichKummer approved these changes

2023-03-15 18:31 UTC, merged