removing the has pseudo selector due to lack of support
carbon-design-system/carbon-for-ibm-dotcom pull request #10504
Opened 2023-05-25 13:44 UTC by pjudge

### Related Ticket(s)

{{Provide url(s) to the related ticket(s) that this pull request addresses}}

### Description

{{Add a human-readable description / detail summary of what the PR is changing and any details around how and why}}

{{If applicable, include a screenshot indicating an example or examples of what the PR is changing in the application}}

### Changelog

**New**

- {{new thing}}

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

2023-05-26 15:08 UTC, kennylam reviewed
@pjudge Thanks for this! The only thing I'd suggest is to use BEM naming conventions, e.g. something like

```css
.#{$prefix}--masthead__l1-dropdown-item--no-link
.#{$prefix}--masthead__l1-dropdown--column-wide
```

2023-05-26 16:40 UTC, andy-blum requested changes

2023-05-26 16:40 UTC, andy-blum commented on packages/web-components/src/components/masthead/masthead-l1.ts
> +      [`no-link`]: noLink,
As @kennylam mentioned, let's BEM-ify this class name.

For the sake of learning here, though:

Readability boost: we could reduce this all to a single line here.

```
const headingClasses = classMap({
      [`${prefix}--masthead__l1-dropdown-heading`]: true,
      "no-link": Boolean(heading.url) === false,
});
```
The `[\`...\`]` version is only necessary if we want to do the string interpolation like in the line above with `${prefix}` (which we will when we make a BEM version)

We can also do simple JS comparisons on the value side of the key/value pair, making the `noLink` variable and it's logic above unnecessary.

2023-05-26 16:40 UTC, andy-blum commented on packages/web-components/src/components/masthead/masthead-l1.ts
> +      [`has-wide`]: hasWideColumn,
See comments at line 767

2023-05-30 19:59 UTC, pjudge commented
Thank you @kennylam and @andy-blum ! I have made the updates you suggested. 👍

2023-06-01 14:53 UTC, kennylam approved these changes
LGTM!

2023-06-01 20:10 UTC, andy-blum approved these changes

2023-06-01 20:13 UTC, andy-blum commented
e2e test failure seems unrelated. Re-running.
<img width="1163" alt="Screenshot 2023-06-01 at 4 12 38 PM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/25532785/ae547686-27a9-41d4-8d48-df7cac0ba6fe">

2023-06-02 03:27 UTC, merged