Rebuild new notice and choice 23 version
carbon-design-system/carbon-for-ibm-dotcom pull request #10653
Opened 2023-07-11 09:50 UTC by deathcave

### Related Ticket(s)

{{Provide url(s) to the related ticket(s) that this pull request addresses}}

### Description

{{Add a human-readable description / detail summary of what the PR is changing and any details around how and why}}

{{If applicable, include a screenshot indicating an example or examples of what the PR is changing in the application}}

### Changelog

**New**

- {{new thing}}

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

2023-07-12 10:12 UTC, deathcave commented
I have read the DCO document and I hereby sign the DCO.

2023-07-12 10:12 UTC, deathcave commented
recheck

2023-07-21 02:59 UTC, deathcave commented
recheck

2023-07-25 03:41 UTC, deathcave commented
I have read the DCO document and I hereby sign the DCO.

2023-07-25 03:41 UTC, deathcave commented
recheck

2023-07-25 09:14 UTC, sanjitbauli requested changes

2023-07-25 09:14 UTC, sanjitbauli commented on packages/web-components/src/components/notice-choice/notice-choice.ts
>      const ncData = getNcContentFromWindow();
unused variable ncData

2023-07-25 09:14 UTC, sanjitbauli commented on packages/web-components/src/components/notice-choice/notice-choice.ts
>        let preText = this.defaultPreText;
unused variable preText

2023-07-25 09:14 UTC, sanjitbauli commented on packages/web-components/src/components/notice-choice/notice-choice.ts
>      const cc = newVal.toLocaleLowerCase();
unused variable cc

2023-07-25 09:14 UTC, sanjitbauli commented on packages/web-components/src/components/notice-choice/notice-choice.ts
>      const lc = countrySettings[newVal.toLocaleLowerCase()].lang;
unused variable lc

2023-07-25 09:14 UTC, sanjitbauli commented on packages/web-components/src/components/notice-choice/notice-choice.ts
> +
unused variable tcHtml

2023-07-25 10:16 UTC, deathcave commented
I have read the DCO document and I hereby sign the DCO.

2023-07-25 10:16 UTC, deathcave commented
recheck

2023-07-26 07:30 UTC, deathcave commented
I have read the DCO document and I hereby sign the DCO.

2023-07-26 11:05 UTC, deathcave commented
I have read the DCO document and I hereby sign the DCO.

2023-07-26 11:05 UTC, deathcave commented
recheck

2023-07-26 11:14 UTC, deathcave commented
I have read the DCO document and I hereby sign the DCO.

2023-07-26 11:15 UTC, deathcave commented
recheck

2023-08-02 12:50 UTC, sanjitbauli commented
@kennylam - following up with the blocker around DCO Assistant and other checks. thanks

2023-08-02 16:28 UTC, kennylam commented
> **DCO Assistant Lite bot:** Thanks for your submission! We ask that you all sign our [Developer Certificate of Origin](https://github.com/carbon-design-system/carbon-dco/blob/main/dco.md) before we can accept your contribution. You can sign the DCO by adding a comment below using this text:
> 
> _**I have read the DCO document and I hereby sign the DCO.**_
> 
> **1** out of **2** committers have signed the DCO.✅
> @kennylam❌ @rajaneesh22
> You can retrigger this bot by commenting **recheck** in this Pull Request

@deathcave Did you change your user name since creating this PR? The DCO assistant is needs a signature from `@rajaneesh22`.

2023-08-02 16:30 UTC, deathcave commented
recheck

2023-08-02 16:46 UTC, kennylam commented
@deathcave Trying to sign with your current user name will not work. It's looking for `@rajaneesh22`. I suggest you close this PR and open a new one.

2023-08-02 16:48 UTC, closed without merging