fix(pricing-table): update to correct Item Not visible
carbon-design-system/carbon-for-ibm-dotcom pull request #10783
Opened 2023-08-02 17:25 UTC by marcelojcs

### Related Ticket(s)

Closes #   https://jsw.ibm.com/browse/ADCMS-3666

### Description

Removed line of code making the pricing table component drop-down not visible on storybook 

{{If applicable, include a screenshot indicating an example or examples of what the PR is changing in the application}}

### Changelog

**Changed**
When viewing the Web Components in the Storybook ( )User can now find the Pricing Table in the Components list where it can be expanded and the component easily viewed.

2023-08-02 17:26 UTC, marcelojcs commented
> _**I have read the DCO document and I hereby sign the DCO.**_

I have read the DCO document and I hereby sign the DCO.

2023-08-03 17:52 UTC, andy-blum requested changes
Changes to manager.js are good, but we need to make sure we're not changing the yarn deps.

2023-08-03 17:52 UTC, andy-blum commented on packages/react/.storybook/manager.js
> +  css += getCss(process.env.DDS_PRICING_TABLE, 'components-pricing-table');
I think this is unnecessary because there's not a react version of the pricing table component.

2023-08-03 17:52 UTC, andy-blum commented on yarn.lock
> -  version: 7.22.5
There shouldn't be any changes to yarn.lock or the cache files. Can we revert those changes?

2023-08-07 15:25 UTC, marcelojcs commented
recheck

2023-08-14 19:24 UTC, andy-blum approved these changes
This looks good now. CI checks are failing intermittently on OOM errors.

2023-08-17 23:02 UTC, andy-blum commented
@marcelojcs it looks like you merged in unrelated code here?

2023-08-24 17:52 UTC, closed without merging

2023-08-30 21:28 UTC, m4olivei commented
Got here from the [Jira ticket](https://jsw.ibm.com/browse/ADCMS-3666). I'm confused, following the issue URL in the replaced title here (eg. https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10880) leads me to a different PR for a different issue.

@marcelojcs did you mean https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10879 ?

For posterity, could you set the title of this PR back to what it was, and instead leave a comment here that reads that it was closed in favor of https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10879 ? That's the common practice, and will be helpful looking back. Thanks!