fix(DPO/C4IBM) - Configure TOC to use smooth scrolling
carbon-design-system/carbon-for-ibm-dotcom pull request #10840
Opened 2023-08-17 16:50 UTC by raluca-danaila

### Related Ticket(s)

Closes # https://jsw.ibm.com/browse/ADCMS-3701

### Description

I have fixed the typo in the table-of-contents from  `scroll-behaviour: smooth;` to  `scroll-behavior: smooth;`

### Changelog

**Changed**

- changed the mistyping: `scroll-behaviour: smooth;` to  `scroll-behavior: smooth;`  in the "table-of-contents" component.

2023-08-17 17:45 UTC, annawen1 approved these changes
LGTM! Thanks! 🎉

2023-08-18 16:24 UTC, ariellalgilmore approved these changes
Looks good! @raluca-danaila if you could just comment below the follow:

> I have read the DCO document and I hereby sign the DCO.

2023-08-21 13:56 UTC, raluca-danaila commented
I have read the DCO document and I hereby sign the DCO.

2023-08-21 15:54 UTC, ariellalgilmore commented
recheck

2023-08-22 18:38 UTC, andy-blum commented
If we want smooth scrolling to be the default we should probably also add that config in to the JS that makes the scrolling happen.

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/src/components/table-of-contents/table-of-contents.ts#L463

https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo#parameters

2023-08-25 13:40 UTC, andy-blum requested changes

2023-08-25 13:40 UTC, andy-blum commented on packages/web-components/src/components/table-of-contents/table-of-contents.ts
>        window.scrollTo(0, targetY);
We have to remove the old scroll behavior for the new one to appear.

2023-09-27 16:09 UTC, m4olivei requested changes
There are some legit CI job failures that are introduced here. See comments.

2023-09-27 16:09 UTC, m4olivei commented on packages/styles/scss/components/tabs-extended/_tabs-extended.scss
> +  #{$prefix}--accordion__content {
This hunk looks like an unintentional change that came in with commit https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10840/commits/323c87167fc803cd51aa117b54e4cc4e89355dd1 . @marcelojcs was this intentional? 

If it is meant to be here, the opening and closing braces are unbalenced, which causes failures in the CI jobs.

2023-09-27 16:09 UTC, m4olivei commented on packages/web-components/src/components/table-of-contents/table-of-contents.ts
> +        top:targetY,
Nit pick.
```suggestion
        top: targetY,
```

2023-09-27 16:09 UTC, m4olivei commented on packages/web-components/src/components/table-of-contents/table-of-contents.ts
> +        behavior:'smooth'
Another nit pick (sorry).
```suggestion
        behavior: 'smooth'
```

2023-09-28 13:55 UTC, closed without merging

2023-09-28 14:39 UTC, marcelojcs commented
Closed in favor of
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10982