Fix/empty l1 arrows
carbon-design-system/carbon-for-ibm-dotcom pull request #10914
Opened 2023-09-05 21:07 UTC by andy-blum

### Related Ticket(s)

[JIRA](https://jsw.ibm.com/browse/ADCMS-3689)

### Description

Hides the L1's overflow scroller buttons when the menu is empty.

### Testing Instructions

In the deploy preview of the masthead w/L1, copy/paste the code below into your console and then resize the browser:

```js
$$('dds-masthead-l1').forEach(l1 => {
    const newData = l1.l1Data;
    newData.menuItems = [];
    l1.l1Data = newData;
    l1.requestUpdate();
})
```

### Changelog

**Changed**

- masthead-l1 will not show overflow scrollers if there are no L1 menu items

2023-09-06 13:41 UTC, m4olivei requested changes
I'm finding that its not hiding the overflow scrollers. Here's what I'm doing:

* Navigate to the [story in iframe mode](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/10914/iframe.html?args=&id=components-masthead--with-l-1&viewMode=story)
* Resize the browser down to where the overflow scrollers appear
* Copy paste the snippet into the dev tools console, run it.
* Scrollers still show up:

![image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/191049/e5007f07-452d-486e-ab9d-944c724bc6e5)

2023-09-06 15:47 UTC, m4olivei approved these changes
Thanks for the clarification @andy-blum . Looks good.

2023-09-06 21:47 UTC, IgnacioBecerra approved these changes

2023-09-27 14:57 UTC, m4olivei commented
Although this is ready to merge it's failing `ci-check / web-components`, which is also failing on `main` [in the same way](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/actions/runs/6300916199/job/17104771560).

@kennylam / @IgnacioBecerra could we get you to bypass and merge? Thanks!

2023-09-27 22:51 UTC, merged