Change(storybook) Create storybook experimental tab
carbon-design-system/carbon-for-ibm-dotcom pull request #10976
Opened 2023-09-27 13:53 UTC by marcelojcs

### Related Ticket(s)

Closes # https://jsw.ibm.com/browse/ADCMS-3995

### Description

Move hidden components to an "experimental" tab on storybook.

### Changelog

**Changed**

Moved the hidden components to an "experimental" tab on  storybook.

**Removed**

Code hiding the components on manager.js

2023-09-29 18:34 UTC, m4olivei approved these changes
I like this a lot. Much cleaner. Like the consistency with Carbon.

2023-09-29 18:34 UTC, m4olivei commented on packages/web-components/.storybook/manager.js
> +});
Nit: Add a newline at the end of the file here.

2023-09-29 18:58 UTC, andy-blum approved these changes
👏 much simpler and more maintainable!

2023-10-10 13:07 UTC, jkaeser requested changes
@marcelojcs Looks like you need to update some URLs in the tests.

2023-10-10 13:07 UTC, jkaeser commented on packages/web-components/src/components/content-block-card-static/__stories__/content-block-card-static.stories.ts
> +  title: 'Experimental/Content block card static',
The e2e test files point to Storybook URLs, and changes like this one have updated those URLs, causing tests to fail. But don't worry, the fixes will be easy! Just find the source tests files and update the paths to match the new pattern. For example, see: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/47a59204d8624c73c2bfdf230e6091d354212cf4/packages/web-components/tests/e2e-storybook/cypress/integration/masthead/cloud/cloud-masthead.e2e.js#L14

2023-10-12 13:11 UTC, m4olivei commented
Just noting that @kennylam and I discussed this at Carbon office hours yesterday, here are my notes:

* I demo'd the solution, grouping experimental stories under a sub-heading in the left sidebar, like [Carbon](https://react.carbondesignsystem.com/?path=/docs/getting-started-welcome--welcome).
* @kennylam would like to get it in. However Storybook, and decisions about the way it's presented to adopters is more left to the designers and leadership. Kenny to check with @oliviaflory and potentially others for their thoughts.

2023-10-12 14:52 UTC, jkaeser approved these changes

2023-10-13 17:00 UTC, oliviaflory commented
This looks good to me. I would like to see the following two stories removed entirely from SB before approving because we are deprecating the pre-configured content blocks in v2 and I'd rather not expose these random ones, even as experimental, in our v1 package:
- content block card static
- content block headlines

2023-10-16 18:05 UTC, marcelojcs commented
@oliviaflory 
[Addresed on the latest commit](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10976#issuecomment-1761827713)

2023-10-16 19:22 UTC, oliviaflory approved these changes
Thank you @marcelojcs

2023-10-17 16:41 UTC, merged