Feat/video cta feature card
carbon-design-system/carbon-for-ibm-dotcom pull request #11160
Opened 2023-11-21 17:55 UTC by m4olivei

### Related Ticket(s)

Closes #11159
[Jira ticket](https://jsw.ibm.com/browse/ADCMS-4274)

### Description

Expand options in the Feature section story to include all supported CTA types. Fix a bug when using the video CTA type, where a double header would appear.

### Changelog

**Changed**

- Expand options in the Feature section story to include all supported CTA types.
- Fix a bug when using the video CTA type, where a double header would appear.

2023-11-24 14:52 UTC, jkaeser requested changes
Code changes and Story behavior look good to me! This surfaces a bug in `<dds-card-cta-footer>`'s hover styles, though:

<img width="1459" alt="Screenshot 2023-11-24 at 9 45 19 AM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/12532727/b9ac790b-59b7-4677-942d-c6ada3829711">

You can reproduce by setting the CTA href to the video ID *before* changing the CTA type to "video". Is this something you can fix while we're here?

2023-11-24 18:01 UTC, jkaeser approved these changes

2023-11-28 20:48 UTC, m4olivei commented
Adjusted the base branch to `v1` seeing as `v2` [merge to main is imminent](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11161).

2023-12-07 15:34 UTC, emyarod approved these changes
looks good to me!

2023-12-08 18:34 UTC, merged