chore(button-group): clean up styles
carbon-design-system/carbon-for-ibm-dotcom pull request #11200
Opened 2023-12-05 16:44 UTC by andy-blum

### Related Ticket(s)

Closes #11198 

### Description

* Breaks button-group and button-group-item styles into separate files
* Migrates component styles solely into web-components package
* Removes unnecessary style imports & rules

### Changelog

**Changed**

- Cleans up styles of `button-group` and `button-group-item`

2023-12-22 14:48 UTC, jkaeser requested changes
The icons have gone missing in the default button story.

2024-01-02 15:04 UTC, m4olivei approved these changes
This is looking good to me. I don't see the same issue that @jkaeser reported for the default button group:
![Monosnap screencast 2024-01-02 10-00-21](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/191049/73bc0107-9346-4b16-8517-0e3fa85a788c)

2024-01-02 21:45 UTC, jkaeser approved these changes

2024-01-02 21:46 UTC, jkaeser commented
Well I'll be, I'm not seeing the missing icons anymore either. Must be ghosts. Approved!

2024-12-23 13:46 UTC, m4olivei commented
@andy-blum is this still worth adopting? When we last were talking about it, John and I were both good with it, and we were only waiting on DPO.

2025-01-30 14:52 UTC, closed without merging