feat(masthead): spacing style regression fix and maintainability refactor
carbon-design-system/carbon-for-ibm-dotcom pull request #11252
Opened 2023-12-19 20:11 UTC by jkaeser

### Related Ticket(s)

Resolves #11251 

### Description

This PR mostly refactors masthead source code to be more maintainable and removes dead code. Other than the style fixes, it should result in no visible changes to the masthead.

### Changelog

**Changed**

- Makes necessary functions available to Sass stylesheets to fix style regressions.
- Deprecates the `navLinks` Masthead Composite property in favor of the more descriptive `l0Data` property. 
- Improves organization and clarity of the Masthead Composite source file.

**Removed**

- Removes Cloud-specific masthead.
- Removes references to v1 data structures that are no longer in use.

2023-12-27 15:18 UTC, m4olivei requested changes
Static review looks good. Lots to love about all the cleanup and refactor.

The [Web Components Storybook job](https://dbg-digital-design-team-jenkins.swg-devops.com/job/Carbon%20for%20IBM.com%20-%20Deploy%20Preview%20-%20Web%20Components/10286/console) is failing with this error:

```
[14:35:45] 'build:dist:rtl:dev' errored after 1.25 min
[14:35:45] Error: Could not resolve entry module (src/components/masthead/cloud/index.ts).
    at error (/home/jenkins/agent/workspace/Carbon for IBM.com - Deploy Preview - Web Components/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.loadEntryModule (/home/jenkins/agent/workspace/Carbon for IBM.com - Deploy Preview - Web Components/node_modules/rollup/dist/shared/rollup.js:22306:20)
    at async Promise.all (index 1)
```

Looks like there is a leftover [cloud reference in the Rollup config here](https://github.com/jkaeser/carbon-for-ibm-dotcom/blob/feat/masthead-v2-cleanup/packages/web-components/tools/get-rollup-config.js#L106-L108).

2024-01-02 14:50 UTC, jkaeser commented on packages/web-components/src/components/masthead/masthead-composite.ts
>      const level0Items = menuItems.map((elem: L0MenuItem, i) => {
I'll admit, I avoided this one since it's so gnarly. Thanks for a nudge in the right direction 😄

2024-01-02 14:56 UTC, jkaeser commented on packages/web-components/src/components/masthead/masthead-composite.ts
>      const level0Items = menuItems.map((elem: L0MenuItem, i) => {
I took another look at it and changed my mind again 😆 This refactor is going to be very complicated and deserves its own PR.

2024-01-02 15:23 UTC, m4olivei commented on packages/web-components/src/components/masthead/masthead-composite.ts
>      const level0Items = menuItems.map((elem: L0MenuItem, i) => {
Heh, fair enough.

2024-01-05 18:47 UTC, kennylam approved these changes

2024-01-09 20:11 UTC, m4olivei approved these changes
Looks great! Thanks for the search fix.

2024-01-11 17:55 UTC, merged