fix(content-group): adding h-tags to headings
carbon-design-system/carbon-for-ibm-dotcom pull request #11738
Opened 2024-04-23 14:08 UTC by marcelojcs

### Related Ticket(s)

[Jira](https://jsw.ibm.com/browse/ADCMS-4630)

>The H3 and H4 headings are not properly configured in the AEM template. They should be tagged as the H1 and H2 (from the same AEM template). Otherwise, they won't have the same SEO relevancy because it's not recognized as H2 & H3.
### Description

Adding the respective H tags to content-group-heading and content-item-heading components.

2024-04-23 18:32 UTC, marcelojcs commented
# V2 version of this PR
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11739

2024-04-25 15:48 UTC, andy-blum requested changes

2024-04-25 15:48 UTC, andy-blum commented on packages/web-components/src/components/content-group/content-group-heading.ts
> +    return html` <h3><slot></slot></h3> packages/web-components/src/components/content-group/content-group-heading.ts`;
```suggestion
    return html` <h3><slot></slot></h3>`;
```

2024-04-26 18:31 UTC, andy-blum commented
It seems that in addition to adding the h3/h4 elements to the shadowroot, we'll need to remove the `role` and `aria-level` properties in use here. As it is now, the headings appear twice in screen readers.

<img width="1155" alt="Screenshot 2024-04-26 at 2 29 13 PM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/25532785/43837546-1552-407c-a8d6-1469bc835826">

2024-05-06 16:39 UTC, jkaeser approved these changes
Code changes here look good to me!

2024-05-06 20:29 UTC, andy-blum commented
There are some subtle but noticable differences in the typography with the new heading elements. Can we get some designer input on what this is supposed to be rendering as?

<img width="449" alt="Screenshot 2024-05-06 at 4 26 57 PM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/25532785/81fd902c-2b8a-4e3f-a12f-968c491830e2">
<img width="449" alt="Screenshot 2024-05-06 at 4 27 37 PM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/25532785/bfdc3a2c-621c-4e10-a183-1f1e794db448">

2024-05-06 20:38 UTC, RichKummer commented
Hey @marcelojcs , I'm seeing the heading for `content item` rendering differently than it should. It should use the fixed`$heading-02` token for the heading in the v1 package.

**This PR:**
<img width="749" alt="Screenshot 2024-05-06 at 4 27 39 PM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/15643582/124b1245-7fdd-4c20-b933-21a20eb99521">

**Spec samples:**
<img width="604" alt="Screenshot 2024-05-06 at 4 34 10 PM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/15643582/ded5c95e-564f-40e9-aeae-faafee29f91e">

2024-05-07 19:16 UTC, RichKummer commented
Hey @marcelojcs and @andy-blum , 

`content item` looks fixed. I noticed that for `content group`, the heading does not appear to be updating its size as `$expressive-heading-04` across breakpoints. It should be `28px` up to `@lg` and then update to `32px` for `@lg – @max`.

Right now, I only see the heading render as `28px` across breakpoints.

2024-05-08 17:04 UTC, marcelojcs commented
@RichKummer 
Addressed in my latest commit.

2024-05-08 17:30 UTC, RichKummer commented
Thanks @marcelojcs ! Both `content item` and `group` look fixed. I did see that for some reason the `content item horizontal`'s header updated to a different type token than it should.

It should appear with the heading as `$expressive-heading-03` 

<img width="1140" alt="Screenshot 2024-05-08 at 1 29 12 PM" src="https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/15643582/933d9955-8b5d-464a-b81e-dc8605c7508f">

2024-05-08 18:39 UTC, andy-blum commented
@RichKummer updated font rules to inherit their `font` `letter-spacing` and `line-height` rules from the parent components.

2024-05-08 19:09 UTC, RichKummer approved these changes
@marcelojcs @andy-blum Thanks for the fixes! LGTM

2024-05-08 19:28 UTC, merged

2024-05-08 19:28 UTC, andy-blum approved these changes