feat(background-media): add shadow parts to bg-media
carbon-design-system/carbon-for-ibm-dotcom pull request #11798
Opened 2024-05-17 21:06 UTC by bruno-amorim

### Related Ticket(s)

[ADCMS-5036](https://jsw.ibm.com/browse/ADCMS-5036)

### Description

Adding shadow parts to Background Media component so that it can be styled outside the shadow tree.

### Changelog

Shadow parts added to Background Media. 
Snapshots updated

2024-05-20 13:47 UTC, jkaeser requested changes
Good call updating the unit test snapshots!

The only critique I have is that your part names don't have a consistent style... some are using the block + element part of BEM naming (e.g. `video-player__controls`), and some are using block + modifier (e.g. `background-media--item`). Can you make these consistent?

2024-05-20 13:58 UTC, andy-blum requested changes

2024-05-20 13:58 UTC, andy-blum commented on packages/web-components/src/components/background-media/background-media.ts
> +        part="video-player__controls"
```suggestion
        part="controls"
```

2024-05-20 13:58 UTC, andy-blum commented on packages/web-components/src/components/background-media/background-media.ts
> +        part="background-media--gradient"
```suggestion
        part="gradient"
```

2024-05-20 13:58 UTC, andy-blum commented on packages/web-components/src/components/background-media/background-media.ts
> +        part="background-media--container"
```suggestion
        part="container"
```

2024-05-20 13:58 UTC, andy-blum commented on packages/web-components/src/components/background-media/background-media.ts
> +          part="background-media--item"
```suggestion
          part="item"
```

2024-05-20 13:59 UTC, andy-blum commented
See https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11796#pullrequestreview-2066279339

2024-05-21 18:00 UTC, jkaeser approved these changes

2024-05-21 19:38 UTC, andy-blum approved these changes

2024-05-21 20:35 UTC, merged