feat(footer): add footer shadow parts
carbon-design-system/carbon-for-ibm-dotcom pull request #11845
Opened 2024-06-04 19:14 UTC by bruno-amorim

### Related Ticket(s)

[ADCMS-5147](https://jsw.ibm.com/browse/ADCMS-5147)

### Description

Adding shadow parts to the footer component to allow light customizations to component internals.

2024-06-06 14:06 UTC, jkaeser reviewed
Looking good to me, but the ci-checks are failing. Can you take a look, @bruno-amorim?

2024-06-06 19:45 UTC, jkaeser approved these changes

2024-06-10 13:55 UTC, andy-blum requested changes
There are some component files that don't seem to have the necessary part attributes:
* legal-nav is missing some elements
* combo-box doesn't seem to have any part attributes

2024-06-13 15:38 UTC, m4olivei requested changes
Few that I found were missing still.

Not part of the current diff, but I also found one missing in the = `<c4d-legal-nav-cookie-preferences-placeholder>` element:

[c4d-legal-nav-cookie-preferences-placeholder](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/feat/footer-shadow-parts/packages/web-components/src/components/footer/legal-nav-cookie-preferences-placeholder.ts#L55)

2024-06-13 15:38 UTC, m4olivei commented on packages/web-components/src/components/footer/footer-nav-group.ts
>          <ul>
Missing a `part` attribute here.

2024-06-13 15:38 UTC, m4olivei commented on packages/web-components/src/components/footer/legal-nav.ts
>                <ul>
Missing a `part` attribute here. I'd suggest naming the above `<div>` on line 85 as `legal-nav-list-container` and this`<ul>` take the name `legal-nav-list`.

2024-06-13 15:38 UTC, m4olivei commented on packages/web-components/src/components/footer/legal-nav.ts
>                <ul>
Missing a `part` attribute here. Recommend `adjunct-links-list`.

Also, review lines 100-111 below. Use the same `legal-nav*` part names as above lines 81-98. If you look at the Footer > Micro story, you can see how these are presently missing.

2024-06-14 21:24 UTC, m4olivei approved these changes

2024-06-14 21:24 UTC, merged