feat(search-with-typeahead): add shadow parts
carbon-design-system/carbon-for-ibm-dotcom pull request #11850
Opened 2024-06-06 12:22 UTC by Valentin-Sorin-Nicolae

[ADCMS-5176](https://jsw.ibm.com/browse/ADCMS-5176)

Description

All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "search-with-typeahead" component.

Changelog

New

Adding the shadow parts for the "search-with-typeahead" component and documentation

2024-06-06 14:50 UTC, jkaeser requested changes
Thanks for your work here, it's looking great! I left some suggestions to simplify things and make them a little more consistent. Please be sure to update the `@ccspart` docs to match new names.

2024-06-06 14:50 UTC, jkaeser commented on packages/web-components/src/components/search-with-typeahead/search-with-typeahead-item.ts
> +      part="search-with-typeahead-item-highlighted"
```suggestion
      part="item item-highlighted"
```

2024-06-06 14:50 UTC, jkaeser commented on packages/web-components/src/components/search-with-typeahead/search-with-typeahead-item.ts
> +        part="search-with-typeahead-item-container"
```suggestion
        part="item-container"
```

2024-06-06 14:50 UTC, jkaeser commented on packages/web-components/src/components/search-with-typeahead/scoped-search-dropdown-mobile.ts
> + * @csspart select-input - The input selector. Usage `c4d-scoped-search-dropdown-mobile::part(select-input)`
```suggestion
 * @csspart select-option - An option in the select list. Usage `c4d-scoped-search-dropdown-mobile::part(select-option)`
 * @csspart select-optgroup - An optgroup in the select list. Usage `c4d-scoped-search-dropdown-mobile::part(select-optgroup)`
 * @csspart helper-text - The helper text. Usage `c4d-scoped-search-dropdown-mobile::part(helper-text)`
 * @csspart form-requirement - The message that appears on invalid input. Usage `c4d-scoped-search-dropdown-mobile::part(form-requirement)`
 * @csspart label-text - The label text. Usage `c4d-scoped-search-dropdown-mobile::part(label-text)`
 * @csspart select-input-wrapper - The select input wrapper. Usage `c4d-scoped-search-dropdown-mobile::part(select-input-wrapper)`
 * @csspart select-input - The input selector. Usage `c4d-scoped-search-dropdown-mobile::part(select-input)`
```

2024-06-06 14:50 UTC, jkaeser commented on packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts
> +          part="combobox-form"
```suggestion
          part="container"
```

2024-06-06 14:50 UTC, jkaeser commented on packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts
> +                  part="search-dropdown"
```suggestion
                  part="dropdown"
```

2024-06-06 14:50 UTC, jkaeser commented on packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts
> +                  part="search-dropdown-mobile"
```suggestion
                  part="dropdown-mobile"
```

2024-06-06 14:50 UTC, jkaeser commented on packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts
> +                            part="search-with-typeahead-item"
```suggestion
                            part="suggestion-item"
```

2024-06-06 14:50 UTC, jkaeser commented on packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts
> +                            part="search-with-typeahead-item"
```suggestion
                            part="suggestion-item"
```

2024-06-06 14:50 UTC, jkaeser commented on packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts
> +                                  part="search-with-typeahead-item"
```suggestion
                                  part="suggestion-item"
```

2024-06-06 14:50 UTC, jkaeser commented on packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts
> +              part="search-actions">
```suggestion
              part="actions">
```

2024-06-06 14:50 UTC, jkaeser commented on packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts
> +            <div class="${prefix}--header__search--actions" part="search-icon">
```suggestion
            <div class="${prefix}--header__search--actions" part="actions actions actions--leadspace">
```

2024-06-06 14:50 UTC, jkaeser commented on packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts
> +                        part="search-with-typeahead-item"
```suggestion
                        part="suggestion-item"
```

2024-06-13 17:08 UTC, m4olivei commented
Apologies for the force push. Fixing the merge conflict got weird.

2024-06-13 18:48 UTC, m4olivei approved these changes
LGTM

2024-06-13 18:48 UTC, merged