feat(locale-modal): add shadow parts
carbon-design-system/carbon-for-ibm-dotcom pull request #11865
Opened 2024-06-12 12:56 UTC by marcelojcs

### Related Ticket(s)

[JIRA](https://jsw.ibm.com/browse/ADCMS-5167)

### Description

{All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles.
R is changing in the application}}

### Changelog

**New**

Added Shadow Parts to the locale-modal component

2024-06-12 13:43 UTC, andy-blum requested changes
This needs work still. Try searching the `locale-modal` directory for instances of "html`" There are some spots that have been missed. Also, the "-composite" component renders in the light-dom so we don't need to add parts to anything it renders.

2024-06-12 18:19 UTC, marcelojcs commented
@andy-blum 
Changes Addressed in my latest commit

2024-06-13 15:43 UTC, m4olivei commented on packages/web-components/src/components/locale-modal/locale-search.ts
> +          <p class="${c4dPrefix}--locale-modal__search-text" part="seach-text">
```suggestion
          <p class="${c4dPrefix}--locale-modal__search-text" part="search-text">
```

2024-06-13 15:46 UTC, m4olivei commented on packages/web-components/src/components/locale-modal/locale-search.ts
> +            part="polite"></div>
`polite` refers to how [`aria-live` updates](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-live) behave for users of assistive tech, it doesn't really describe this element. I want to suggest something like `aria-updates`
```suggestion
            part="aria-updates"></div>
```

2024-06-13 15:56 UTC, m4olivei commented on packages/web-components/src/components/locale-modal/region-item.ts
> +        part="button disabled-button">
Lets follow a convention we've been using elsewhere:
```suggestion
        part="button button--disabled">
```

2024-06-13 15:57 UTC, m4olivei commented on packages/web-components/src/components/locale-modal/region-item.ts
> +            part="button enabled-button">
Lets follow a convention we've been using elsewhere:
```suggestion
            part="button button--enabled">
```

2024-06-13 18:53 UTC, m4olivei approved these changes
Thanks for the changes! All set here.

2024-06-13 18:53 UTC, merged