feat(masthead): adding shadow parts
carbon-design-system/carbon-for-ibm-dotcom pull request #11881
Opened 2024-06-20 13:11 UTC by bruno-amorim

### Related Ticket(s)

[ADCMS-5170](https://jsw.ibm.com/browse/ADCMS-5170)

### Description

Adding shadow parts to the Masthead component so it can be styles outside of the Shadow Tree.
Snapshots updated.

2024-06-20 15:11 UTC, jkaeser requested changes
Remember, given the way these will be used we don't need to prefix each part name with the component name. E.g.
```css
/* Redundant */
c4d-left-nav-menu-category-heading::part(left-nav-menu-category-h2) { ... }

/* Not redundant */
c4d-left-nav-menu-category-heading::part(heading) { ... }
```

I'd also encourage you to take a look at the markup as rendered in the browser to get a better idea of how all these pieces are actually used. While looking at class names for hints is good, they don't always necessarily match how the element is actually used. See my comment on `<c4d-left-nav-menu-section>`'s back button for an example of what I mean.

It looks like all of these part names can be simplified. I left some notes for how I might go about doing that for some components. Can you do another round trying to match that approach? Thanks!

2024-06-20 15:11 UTC, jkaeser commented on packages/web-components/src/components/masthead/left-nav-menu-section.ts
> +                part="masthead-side-nav-submemu"
I see that you're referencing a CSS class to come up with the name here, but in this case, I think there are a couple issues with that:
1. We don't need to copy over typos
2. This isn't really functioning as a submenu. Rather, it's functioning as a menu item and a back button wrapper:
```suggestion
                part="menu-item back-button-wrapper"
```

2024-06-20 15:11 UTC, jkaeser commented on packages/web-components/src/components/masthead/left-nav-menu-section.ts
> +                  part="side-nav-link"
```suggestion
                  part="menu-link back-button"
```

2024-06-20 15:11 UTC, jkaeser commented on packages/web-components/src/components/masthead/left-nav-menu-section.ts
> +                    part="side-nav-link-text"
```suggestion
                    part="menu-link-text back-button-text"
```

2024-07-04 13:08 UTC, bruno-amorim commented
Hey guys @andy-blum @Valentin-Sorin-Nicolae @marcelojcs @m4olivei 

I have addressed the comments from John, can you please check it now? I have just simplified the naming convention for all the shadow parts.

Thank you!!

2024-07-05 13:52 UTC, m4olivei requested changes
Few things found. Overall nice work. Almost there!

2024-07-05 13:52 UTC, m4olivei commented on packages/web-components/src/components/masthead/left-nav-menu-section.ts
> +                  part="menu-link back-button"
The `back-button` part needs documentation.

2024-07-05 13:52 UTC, m4olivei commented on packages/web-components/src/components/masthead/masthead-global-bar.ts
> +      <div part="ce-header-global-container" class="${classes}">
I think we can simplify this to just `container`.
```suggestion
      <div part="container" class="${classes}">
```

2024-07-05 13:52 UTC, m4olivei commented on packages/web-components/src/components/masthead/masthead-l1.ts
> +    return `${c4dPrefix}-l1-dropdown-toggle`;
Is this change intentional? Does not seem releated to the shadow parts 🤔

2024-07-05 13:52 UTC, m4olivei commented on packages/web-components/src/components/masthead/masthead-menu-button.ts
> +        part="sentinel-button"
Maybe add a modifier part so we can target the specific button if needed.
```suggestion
        part="sentinel-button sentinel-button--${side}"
```

2024-07-05 13:52 UTC, m4olivei commented on packages/web-components/src/components/masthead/megamenu-category-link.ts
> -            <div part="link-heading">
I'd rather leave this as is, in case it's already being used in the wild. This is an API break.

2024-07-05 13:52 UTC, m4olivei commented on packages/web-components/src/components/masthead/megamenu-category-link.ts
> -      <span part="link-description">
Same here. Let's leave as it.

2024-07-05 13:52 UTC, m4olivei commented on packages/web-components/src/components/masthead/top-nav.ts
> +                        class="${prefix}--sub-content-left"></div>
Missed a `<div>` element in this file on line 601: `<div class="${caretLeftContainerClasses}">`

2024-07-05 13:52 UTC, m4olivei commented on packages/web-components/src/components/masthead/top-nav.ts
> +                    class="${prefix}--header__nav-content">
Missed a `<div>` element on line 639: `<div class="${prefix}--sub-content-left"></div>`

2024-07-08 18:47 UTC, m4olivei requested changes
Small nits. Will commit.

2024-07-08 18:47 UTC, m4olivei commented on packages/web-components/src/components/masthead/masthead-menu-button.ts
> + * @csspart sentinel-button-start - The start sentinel button for managing focus. Usage: `c4d-masthead-menu-button::part(sentinel-button-start)`
```suggestion
 * @csspart sentinel-button--start - The start sentinel button for managing focus. Usage: `c4d-masthead-menu-button::part(sentinel-button--start)`
```

2024-07-08 18:47 UTC, m4olivei commented on packages/web-components/src/components/masthead/masthead-menu-button.ts
> + * @csspart sentinel-button-end - The end sentinel button for managing focus. Usage: `c4d-masthead-menu-button::part(sentinel-button-end)`
```suggestion
 * @csspart sentinel-button--end - The end sentinel button for managing focus. Usage: `c4d-masthead-menu-button::part(sentinel-button--end)`
```

2024-07-08 18:47 UTC, m4olivei commented on packages/web-components/src/components/masthead/masthead-menu-button.ts
> +        part="sentinel-button sentinel-button-${side}"
```suggestion
        part="sentinel-button sentinel-button--${side}"
```

2024-07-08 19:39 UTC, m4olivei requested changes
Sorry found a couple more.

2024-07-08 19:39 UTC, m4olivei commented on packages/web-components/src/components/masthead/masthead-l1.ts
>                      <li>
This `<li>` is missing a part attribute. Maybe `l1-dropdown-menu-item`.

2024-07-08 19:39 UTC, m4olivei commented on packages/web-components/src/components/masthead/masthead-l1.ts
> +                class="${prefix}--masthead__l1-dropdown-announcement">
Not able to comment directly on it, but line 511 below is missing a `part` attribute. Probably `dropdown-links` would work.

2024-07-08 19:39 UTC, m4olivei commented on packages/web-components/src/components/masthead/masthead-l1.ts
> +                <a part="l1-dropdown-viewall"
This is good. Found another missing `part` on line 946. The `<a>` around an L1 column heading. I would suggest `part="l1-dropdown-item-link l1-dropdown-item-link--heading"`

2024-07-09 17:01 UTC, m4olivei approved these changes

2024-07-09 17:01 UTC, merged