feat(pagination): adding shadow parts
carbon-design-system/carbon-for-ibm-dotcom pull request #11930
Opened 2024-07-17 20:00 UTC by bruno-amorim

### Related Ticket(s)

[ADCMS-5336](https://jsw.ibm.com/browse/ADCMS-5336)

### Description

Adding shadow parts to the pagination component, so that it can be styled outside of the shadow tree.
Snapshots updated.

2024-07-17 20:16 UTC, m4olivei requested changes

2024-07-17 20:16 UTC, m4olivei commented on packages/carbon-web-components/src/components/pagination/pagination.ts
> +          part="pagination-text-left"
Lets drop the `pagination-` prefix from all the new part names in this component. It's redundant when you consider the selectors a parent page would be using, eg. `cds-pagination::part(pagination-text-left)`. 

Also, given there are a few elements that share the class `cds--pagination__text`, I think we could improve by using two part names, one generic so parent pages could target them all in one selector, and one specific, using a modifier. Using this one as an example, `part="text text--left"`.

2024-07-17 20:16 UTC, m4olivei commented on packages/carbon-web-components/src/components/pagination/pagination.ts
> + * @csspart pagination-text-right - The left pagination text. Usage: `cds-pagination::part(pagination-text-right)`
Name and description mix 'right' and 'left'.

2024-07-17 20:38 UTC, m4olivei requested changes

2024-07-17 20:38 UTC, m4olivei commented on packages/carbon-web-components/src/components/pagination/pagination.ts
>          <cds-select
Missing `part` attributes on `<cds-select>` and `<cds-select-item>` elements, both part of the shadow root for this component.

2024-07-17 20:38 UTC, m4olivei commented on packages/carbon-web-components/src/components/pagination/pagination.ts
> +                part="pagination-text-right"
Just below here from lines 394-424, again, missing `part` attributes on `<cds-select>` and `<cds-select-item>` elements, both part of the shadow root for this component.

2024-07-17 20:38 UTC, m4olivei commented on packages/carbon-web-components/src/components/pagination/pagination.ts
>            <cds-button
Missing `part` attribute on `<cds-button>` components. Here and on line 447.

2024-07-18 14:10 UTC, bruno-amorim commented
Hi @m4olivei,
All your comments have been addressed. Can you please take a look again?

Thanks a lot for your help!

2024-07-18 15:04 UTC, m4olivei requested changes

2024-07-18 15:04 UTC, m4olivei commented on packages/carbon-web-components/src/components/pagination/pagination.ts
> + * @csspart text-left - The left pagination text. Usage: `cds-pagination::part(text-left)`
Sorry, I wasn't clear before. We've been using a convention inspired by [BEM](https://getbem.com/naming/#modifier), where the variant or modifier is named with a double-dash separator. For instance, see @marcelojcs 's recent change to the [code-snippet element](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/feat/v2-shadow-parts/packages/carbon-web-components/src/components/code-snippet/code-snippet.ts#L436). If you aren't familiar with BEM, that page is well worth the read. It'll also help make sense of many of the class names you see in the Carbon projects, as well as in AEM. 
```suggestion
 * @csspart text--left - The left pagination text. Usage: `cds-pagination::part(text--left)`
```

2024-07-18 15:04 UTC, m4olivei commented on packages/carbon-web-components/src/components/pagination/pagination.ts
> + * @csspart text-right - The right pagination text. Usage: `cds-pagination::part(text-right)`
```suggestion
 * @csspart text--right - The right pagination text. Usage: `cds-pagination::part(text--right)`
```

2024-07-18 15:04 UTC, m4olivei commented on packages/carbon-web-components/src/components/pagination/pagination.ts
> +          part="text text-left"
```suggestion
          part="text text--left"
```

2024-07-18 15:04 UTC, m4olivei commented on packages/carbon-web-components/src/components/pagination/pagination.ts
> +                part="text text-right"
```suggestion
                part="text text--right"
```

2024-07-18 17:26 UTC, m4olivei approved these changes

2024-07-18 17:27 UTC, merged