fix(callout-quote): non-latin typefaces do not support serif
carbon-design-system/carbon-for-ibm-dotcom pull request #11991
Opened 2024-08-27 20:59 UTC by bruno-amorim

### Related Ticket(s)

[ADCMS-6085](https://jsw.ibm.com/browse/ADCMS-6085)

### Description

When using the callout-quote component, the shadowroot styles render the blockquote element in a serif font. (e.g. [mainframe application modernization](https://www.ibm.com/mainframe-application-modernization))

In non-latin fonts, however, there isn't a serif version of those typefaces, leading to the components rendering non-plex characters. (e.g. [MAM in Japanese](https://www.ibm.com/jp-ja/mainframe-application-modernization))

2024-08-29 13:48 UTC, andy-blum requested changes

2024-08-29 13:48 UTC, andy-blum commented on packages/styles/scss/components/callout-quote/_callout-quote.scss
> +    &[lang="cn"],
```suggestion
    &[lang="zh"],
```

2024-08-29 13:48 UTC, andy-blum commented on packages/styles/scss/components/callout-quote/_callout-quote.scss
> +    &[lang="cn"],
CN is the country code for China - we want the language code "ZH"

2024-08-29 13:48 UTC, andy-blum commented on packages/styles/scss/components/quote/_quote.scss
> +    &[lang="cn"],
```suggestion
    &[lang="zh"],
```

2024-08-29 13:55 UTC, andy-blum approved these changes

2024-09-16 16:51 UTC, kennylam approved these changes

2024-09-16 17:56 UTC, merged

2024-09-17 14:50 UTC, m4olivei commented on packages/web-components/src/components/quote/quote.ts
> +import { LocaleAPI } from '../../internal/vendor/@carbon/ibmdotcom-services/services/Locale';
Found a bug here for downstream adopters. This compiles to:

```
import { LocaleAPI } from "../../internal/vendor/@carbon/ibmdotcom-services/services/Locale.js";
```
Which does not exist and throws errors with at least some bundler configurations. This adopter is using Webpack:

```
ERROR in ./node_modules/@carbon/ibmdotcom-web-components/es/components/quote/quote.js 31:0-96
Module not found: Error: Can't resolve '../../internal/vendor/@carbon/ibmdotcom-services/services/Locale.js' in '/Users/m4olivei/projects/ibm-cms-cloud-carbon-v2/ui.frontend.idl/node_modules/@carbon/ibmdotcom-web-components/es/components/quote'
```

It's also reproducible with a simple vite configuration: https://stackblitz.com/github/m4olivei/carbon-demo/tree/quote-test?file=components.js

Will file an issue and fix.

2024-09-17 14:54 UTC, m4olivei commented on packages/web-components/src/components/quote/quote.ts
> +import { LocaleAPI } from '../../internal/vendor/@carbon/ibmdotcom-services/services/Locale';
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/12034