Feat/addressing components with missing shadow parts
carbon-design-system/carbon-for-ibm-dotcom pull request #12016
Opened 2024-09-10 20:20 UTC by bruno-amorim

### Related Ticket(s)

[ADCMS-6148](https://jsw.ibm.com/browse/ADCMS-6148)

### Description

I have added the last round of shadow parts that we've missed through our shadow part tickets.

2024-09-11 19:42 UTC, m4olivei requested changes
Few minor changes here and there.

2024-09-11 19:42 UTC, m4olivei commented on packages/web-components/src/components/markdown/markdown.ts
> +          ordered ? 'ordered-list' : 'unordered-list'
Lets add a consistent name to either case so if someone wanted to target regardless of the kind of list, they could.
```suggestion
          ordered ? 'list ordered-list' : 'list unordered-list'
```

2024-09-11 19:42 UTC, m4olivei commented on packages/web-components/src/components/markdown/markdown.ts
> + * @csspart unordered-list - The unordered list element. Usage: `c4d-markdown::part(unordered-list)`
```suggestion
 * @csspart unordered-list - The unordered list element. Usage: `c4d-markdown::part(unordered-list)`
 * @csspart list - The list element. Usage: `c4d-markdown::part(list)`
```

2024-09-11 19:42 UTC, m4olivei commented on packages/web-components/src/components/masthead/left-nav-menu.ts
> + *  * @csspart side-nav-item-container - The container for the side navigation item. Usage: `c4d-left-nav-menu::part(side-nav-item-container)`
```suggestion
 *  @csspart side-nav-item-container - The container for the side navigation item. Usage: `c4d-left-nav-menu::part(side-nav-item-container)`
```

2024-09-11 19:42 UTC, m4olivei commented on packages/web-components/src/components/masthead/masthead-l1.ts
> +      ? html`<div class=${classes} part="column-wide">${renderedSections}</div>`
Let’s call this `dropdown-column` generically, and then conditionally add a wide or narrow modifier, eg.
```suggestion
      ? html`<div class=${classes} part="dropdown-column${hasWide && !isWide ? ' dropdown-column--narrow' :  hasWide && isWide ? ' dropdown-column--wide' : ''}">${renderedSections}</div>`
```
Also update docs accordingly.

2024-09-11 19:42 UTC, m4olivei commented on packages/web-components/src/components/masthead/masthead-profile.ts
> + * @csspart header-menu-ul - The header menu ul element. Usage: `c4d-masthead-contact::part(header-menu-ul)`
```suggestion
 * @csspart header-menu - The header menu element. Usage: `c4d-masthead-contact::part(header-menu)`
```

2024-09-11 19:42 UTC, m4olivei commented on packages/web-components/src/components/masthead/masthead-profile.ts
> +        part="header-menu-ul">
```suggestion
        part="header-menu">
```

2024-09-11 19:42 UTC, m4olivei commented on packages/web-components/src/components/notice-choice/notice-choice.ts
> + * @csspart span-container - The span container. Usage `c4d-notice-choice::part(span-container)`
```suggestion
 * @csspart container - The container. Usage `c4d-notice-choice::part(container)`
```

2024-09-11 19:42 UTC, m4olivei commented on packages/web-components/src/components/notice-choice/notice-choice.ts
> +    return html`<span part="span-container">
```suggestion
    return html`<span part="container">
```

2024-09-13 13:05 UTC, m4olivei requested changes
Looking good! Just one missing change for documentation.

2024-09-13 13:05 UTC, m4olivei commented on packages/web-components/src/components/masthead/masthead-l1.ts
> + * @csspart column-wide - The column wide container Usage: `c4d-masthead-l1::part(column-wide)`
Need to update the documention for the new naming.

2024-09-16 14:08 UTC, m4olivei approved these changes

2024-09-16 16:49 UTC, kennylam approved these changes

2024-09-16 17:24 UTC, merged