fix(conten-group-heading): render h3 tag to light DOM
carbon-design-system/carbon-for-ibm-dotcom pull request #12074
Opened 2024-10-14 13:44 UTC by marcelojcs

### Related Ticket(s)
[JIRA](https://jsw.ibm.com/browse/ADCMS-5810)

### Description

Google analytics tools can't pickup on heading elements in shadowroots. We've been asked to adjust content-group-heading elements.
This PR addresses the issue by rendering an h3 element to the light DOM.

### Changelog
the content-group-heading component will now wrap the slotted markup in and <h3> and write the result to the light DOM for SEO purposes

2024-10-14 17:50 UTC, andy-blum submitted a review, later dismissed

2024-10-17 12:30 UTC, andy-blum requested changes

2024-10-17 12:30 UTC, andy-blum commented on packages/web-components/src/components/content-group/content-group-heading.ts
> +    return html`<h3 part="heading"><slot></slot></h3>`;
This won't work - the big thing we're trying to do is put the `<h3>` in the light dom rather than the shadow DOM.

2024-10-17 12:30 UTC, andy-blum commented on packages/styles/scss/internal/content-group/_content-group.scss
> +    h3 {
Can we avoid the style regressions with `::slotted(h3)`?

2024-10-24 21:07 UTC, m4olivei approved these changes
LGTM

2024-10-25 01:13 UTC, andy-blum approved these changes

2024-10-25 01:13 UTC, merged