chore(telemetry): updated telemetry.yml endpoint
carbon-design-system/carbon-for-ibm-dotcom pull request #12075
Opened 2024-10-14 23:50 UTC by IgnacioBecerra

### Description
This PR updates the endpoint within each package's `telemetry.yml` file with the new stable endpoint for the collector. Also, this updates the wording used in the telemetry notice under each README.

### Changelog

**Changed**

- `telemetry.yml` endpoint to new stable endpoint
- updated wording under telemetry notice in each README

2024-10-16 15:21 UTC, m4olivei requested changes
Looks good. Just need to address the CI job. Looks like code formatting is at issue: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/actions/runs/11353018620/job/31577055623?pr=12075

2024-10-16 15:57 UTC, IgnacioBecerra commented
@m4olivei Should be fixed now!

2024-10-16 19:20 UTC, emyarod approved these changes
looks good to me!

2024-10-17 01:49 UTC, m4olivei approved these changes

2024-10-17 01:50 UTC, merged