fix(cta): prevent an infinate loop of fetching video details
carbon-design-system/carbon-for-ibm-dotcom pull request #12084
Opened 2024-10-28 21:25 UTC by m4olivei

### Related Ticket(s)

[ADCMS-6577](https://jsw.ibm.com/browse/ADCMS-6577)

### Description

Prevents an infiniate loop in some situations with vidoe CTA cards.

### Changelog

**Changed**

- Adjusted CTA logic to guard against Kaltura fetch when its already been done.

2024-10-31 16:33 UTC, m4olivei commented on packages/web-components/src/component-mixins/cta/cta.ts
> +        this?.shadowRoot?.querySelector(':first-child')?.offsetWidth > 0
Ended up using a simpler selector so we're not hardcoding card-specific things. I also checked for other CTAMixin uses, and of those I couldn't find any that both used a `videoThumbnailUrl` and were not `C4DCard` children. Those are:

* C4DButton
* C4DButtonGroupItem
* C4DButtonCTA
* C4DLinkWithIcon
* C4DCardFooter
* C4DFeatureCardFooter
* C4DFeatureCTAFooter
* C4DTextCTA

The other way to look at is to see what is actually reading from `videoThumbnailUrl`. Those places are:

* [card.ts](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/src/components/card/card.ts#L163)
* [card-in-card.ts](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/src/components/card-in-card//card-in-card.ts#L31)
* [card-cta.ts](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/src/components/cta/card-cta.ts#L74)
* [feature-cta.ts](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/src/components/cta/feature-cta.ts#L74)

All of those are descendants of `C4DCard`. Does give a good list to test from.

2024-11-01 13:28 UTC, andy-blum commented
The [demo link](https://video-cta-lockup--carbon-demos.netlify.app/) from the issue is updated to use the CDN deploy previews from this PR. While the browser no longer locks up, the modal containing the media isn't popping up either.

I'd expect the card-group-item to open a modal, seed in the iframe from kaltura, and then either play the video or error on a domain restriction.

2024-11-01 13:28 UTC, andy-blum requested changes
changes needed in previous comment

2024-11-01 13:31 UTC, m4olivei commented
> The [demo link](https://video-cta-lockup--carbon-demos.netlify.app/) from the issue is updated to use the CDN deploy previews from this PR. While the browser no longer locks up, the modal containing the media isn't popping up either.
> 
> I'd expect the card-group-item to open a modal, seed in the iframe from kaltura, and then either play the video or error on a domain restriction.

Isn't that the issue that we're working on in [ADCMS-6596](https://jsw.ibm.com/browse/ADCMS-6596)?

2024-11-01 14:05 UTC, andy-blum approved these changes

2024-11-01 15:44 UTC, merged