feat(tile, tile-group): add components
carbon-design-system/carbon-for-ibm-dotcom pull request #12091
Opened 2024-11-01 16:22 UTC by andy-blum

### Related Ticket(s)

https://jsw.ibm.com/browse/ADCMS-6691

### Description

Migrates the `tile` and `tile-group` components from `carbon-for-aem` into `carbon-for-ibmdotcom`

### Changelog

**New**

- adds `c4d-tile`
- adds `c4d-tile-group`

2024-11-01 18:56 UTC, areagan1030 approved these changes

2024-11-04 12:29 UTC, m4olivei requested changes
Noticed a couple of things from a static review perspective. Also, review CI jobs, looks like [at least stylelint is angry](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/actions/runs/11638687608/job/32413835196?pr=12091).

Also comparing the componets on CAEM vs here:

The image ratios are different. Not sure which is correct:

![image](https://github.com/user-attachments/assets/d3f118ad-f251-4c02-b619-edc851591789)

The Tile Group Default and With Image stories lost their knobs configuration.

![image](https://github.com/user-attachments/assets/c8b62c39-b643-4351-b113-f0c0a5326582)

2024-11-04 12:29 UTC, m4olivei commented on packages/web-components/src/components/tile/__stories__/tile-group.stories.ts
> +import { html } from 'lit-element';
We should take the opportunity here to update lit imports to the recommended form. See the [v2 upgrade guide](https://lit.dev/docs/v2/releases/upgrade/#update-packages-and-import-paths). I had a [PR open to do this on CAEM](https://github.ibm.com/webstandards/carbon-for-aem/pull/196/files), never got around to tidying it up, but it stands as a good guide to the changes we need. Doing this change will align well with existing components in the repo.

2024-11-04 12:29 UTC, m4olivei commented on packages/web-components/src/components/tile/__stories__/tile.stories.ts
> +    data-autoid="dds--card__pictogram"
`dds` prefix here. We can probably just drop this `data` attribute I'd think? Was probably copy 🍝  from somewhere long ago.

2024-11-04 12:29 UTC, m4olivei commented on packages/web-components/src/components/tile/tile.scss
> +// @use '@carbon/ibmdotcom-styles/scss/globals/utils/flex-grid' as *;
Remove commented out code.

2024-11-04 12:29 UTC, m4olivei commented on packages/web-components/src/components/tile/tile.scss
> +        aspect-ratio: var(--caem-tile-aspect-ratio, 16 / 9);
Any reason to keep the `caem` prefix here, or can we update this to a `c4d` prefix?

2024-11-04 12:29 UTC, m4olivei commented on packages/web-components/src/components/tile/tile.ts
> +import { classMap } from 'lit-html/directives/class-map.js';
Any directive imports also need updating to [use the `lit` package instead](https://lit.dev/docs/v2/releases/upgrade/#update-directive-imports).

2024-11-11 14:07 UTC, m4olivei requested changes

2024-11-11 14:07 UTC, m4olivei commented on packages/web-components/src/components/tile/__stories__/tile-group.stories.ts
> +    knobs: () => {
The knobs are still not showing up for the tile stories. Looking at other components, it looks like this property is expected to be an object keyed by the component, with a value of this function, eg.

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/src/components/quote/__stories__/quote.stories.ts#L64-L88

2024-11-11 15:27 UTC, m4olivei approved these changes
Looking good now!

2024-11-11 22:12 UTC, merged