fix(leadspace): in storybook adding long copy to copy knob led to button being clipped away
carbon-design-system/carbon-for-ibm-dotcom pull request #12117
Opened 2024-11-21 20:32 UTC by bruno-amorim

### Related Ticket(s)

Closes # https://jsw.ibm.com/browse/ADCMS-6664

### Description

Adding **long** text to the leadspace copy knob leads to clipping the text & CTAs.

Issue:
![image](https://github.com/user-attachments/assets/7f51a789-33a8-463f-a408-b5d8628c7a93)

Fixed:
![image](https://github.com/user-attachments/assets/bcd9b23c-593c-480a-b145-9864408d2b99)

### NOTE
There's an apparent bug in all heading/title knobs in all components, when you try to modify it, we get the below error.
I've been trying to debug this error, but with @m4olivei 's help, we found out it's an issue that's been sitting there for a while now, so It would just be very time consuming for the tiny fix that was the original scope of this ticket
![example3](https://github.com/user-attachments/assets/6c613264-6bc8-4bcf-9bed-7c5a8350f236)

2024-11-21 21:13 UTC, andy-blum requested changes
While this fixes the `medium` leadspace, `super`, `tall`, and `short` still have the ability to overflow & clip

2024-11-22 15:54 UTC, bruno-amorim commented
@andy-blum This latest commit will address your last comment. Thank you!

2024-11-22 16:40 UTC, m4olivei requested changes
I'm seeing a visual regression here for the default values. Most obvious in Super. Comparing current v2 to the deploy preview here:

https://github.com/user-attachments/assets/0bc1374b-0088-4c58-9232-cee07f08af2b

As a sidenote, I was surprised to realize that the Leadspace stories aren't represented in Percy.

2024-11-22 19:44 UTC, andy-blum approved these changes

2024-11-22 20:47 UTC, m4olivei approved these changes

2024-11-22 20:48 UTC, merged