feat(link-list-section): Web component created
carbon-design-system/carbon-for-ibm-dotcom pull request #4651
Opened 2020-12-07 22:14 UTC by RaphaelAmadeu

### Related Ticket(s)

#3376
### Description

Created the web-component version of `LinkListSection` following it's design and functional specs.

2020-12-08 00:41 UTC, asudoh reviewed
LGTM basically, just one thing - Thanks @RaphaelAmadeu!

2020-12-08 00:41 UTC, asudoh commented on packages/web-components/src/components/link-list/link-list.ts
> +
Let's leave this not running for now - We are trying to determine what to do with `sameWidth()`/`sameHeight()` as a whole.

```suggestion
```

2020-12-08 14:27 UTC, asudoh approved these changes
Thanks @RaphaelAmadeu for the update!

2020-12-08 16:24 UTC, jeffchew requested changes
Visually looks broken to me, can you take a look @RaphaelAmadeu ?

<img width="993" alt="Screen Shot 2020-12-08 at 11 23 48 AM" src="https://user-images.githubusercontent.com/1641214/101510418-e9a07380-3947-11eb-808c-682787241aa3.png">

2020-12-09 14:58 UTC, RaphaelAmadeu commented
> Visually looks broken to me, can you take a look @RaphaelAmadeu ?
> 
> <img alt="Screen Shot 2020-12-08 at 11 23 48 AM" width="993" src="https://user-images.githubusercontent.com/1641214/101510418-e9a07380-3947-11eb-808c-682787241aa3.png">
> 
> Also, the props table isn't loading:
> 
> <img alt="Screen Shot 2020-12-08 at 11 25 45 AM" width="1241" src="https://user-images.githubusercontent.com/1641214/101510617-279d9780-3948-11eb-8583-510177a2fc93.png">

I've addressed these issues on my latest commit, thanks!

2020-12-09 15:55 UTC, jeffchew commented
Thanks @RaphaelAmadeu ! can you check the web components ci-checks? probably snapshots...

2020-12-10 20:51 UTC, jeffchew approved these changes
Thank you @RaphaelAmadeu !

2020-12-10 21:23 UTC, merged