feat(link-list): aem improvements to end-of-section type
carbon-design-system/carbon-for-ibm-dotcom pull request #4972
Opened 2021-01-21 20:58 UTC by RaphaelAmadeu

### Related Ticket(s)

#4902 

### Description

End variant of Link List was updated to reflect the new design specs by AEM team.

![image](https://user-images.githubusercontent.com/30945011/105411394-21baf780-5c12-11eb-95b7-2c488694fc3e.png)

2021-01-22 02:04 UTC, asudoh reviewed
Great progress @RaphaelAmadeu!

2021-01-22 02:04 UTC, asudoh commented on packages/web-components/src/components/link-list/link-list.scss
> +  }
There seem many duplicate CSS rules with two columns mode. One way to solve it is:

```css
.#{$dds-prefix}-ce--link-list__list--split {
   /* The common rules */
}

.#{$dds-prefix}-ce--link-list__list--two-columns {
  /* 2-column mode-specific rules */
}

.#{$dds-prefix}-ce--link-list__list--three-columns {
  /* 3-column mode-specific rules */
}
```

```css
.#{$dds-prefix}-ce--link-list__list--split,
.#{$dds-prefix}-ce--link-list__list--three-columns {
   /* The common rules */
}
```

2021-01-22 20:11 UTC, RobertaJHahn commented
@RaphaelAmadeu @StephanieHoman is the designer on this work and should be assigned to review this PR.  Please update the design issue (#4900), letting her know that it is ready and provide the links where she can review it.

2021-01-23 00:38 UTC, asudoh approved these changes
LGTM 👍 - Thanks @RaphaelAmadeu for the update!

2021-01-25 03:03 UTC, jeffchew requested changes
The documentation looks a little light as far as what the type means, and what options there are. Can you describe what types can be passed in, and what each type does?

![Screen Shot 2021-01-24 at 10 02 34 PM](https://user-images.githubusercontent.com/1641214/105656356-03622f80-5e90-11eb-8757-5d78514be5ed.png)

2021-01-27 20:33 UTC, jeffchew approved these changes

2021-01-27 20:46 UTC, merged