feat(cta-block): introduced cta block web component, added it as cta section variant, removed promo group and promo item
carbon-design-system/carbon-for-ibm-dotcom pull request #5530
Opened 2021-03-17 21:04 UTC by rastogir

### Related Ticket(s)

- [#5216](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5216)
- [#5220](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5220)
- [#5221](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5221)

### Description

- Adds `<dds-cta-block>`. This replaces `<dds-promo-group>` and `<dds-promo-item>`. It is based off of `<dds-content-item>`.
- Adds `CtaBlock` variant to `<dds-cta-section>` component. This variant has an additional prop of `Media Type` to switch between image, video, statistic and pictogram. 
- Removes `<dds-promo-group>` and `<dds-promo-item>`.

### Design Specs

- https://ibm.ent.box.com/s/shr0pnhof0yzk2b5lh0nokwopgxxb9rr
![Screen Shot 2021-03-17 at 3 54 43 PM](https://user-images.githubusercontent.com/11525031/111537217-28a94680-8739-11eb-93b7-b8a8008e47db.png)

### Functional Spec

- https://user-images.githubusercontent.com/3793636/108720924-067c2a00-74e7-11eb-8441-44bb8b412dcd.png

### Changelog

**New**

- `<dds-cta-block>` component. 

**Changed**

- `<dds-cta-section>` story updated with `<dds-cta-block>` variant.

**Removed**

- `<dds-promo-group>` and `<dds-promo-item>` component.

2021-03-18 00:33 UTC, asudoh reviewed
Looks a nice improvement. Do you want to create a CodeSandbox example? Thanks @rastogir!

2021-03-18 00:33 UTC, asudoh commented on packages/web-components/src/components/cta-block/__stories__/cta-block.stories.ts
> +        `
I think render-from-data approach complicates the explanation of how to use the component, would you put plain markup here?

2021-03-18 16:13 UTC, photodow requested changes
Thanks @rastogir! Here are some quick high-level things I noticed... Reach out if you have any questions.

1. `CTA block`, and `CTA section` are backwards. What you have as `CTA block` should be `CTA section` and vice versa.
![image](https://user-images.githubusercontent.com/3793636/111657257-43cb9300-87d9-11eb-8d3e-10fb469ab825.png)

2. Casing needs to be fixed. We use sentence casing for these.
```
CTA block
— Default
CTA section
— Default
— With content items
— With link list
— CTA block
```

3. Is `CTA section` missing bottom spacing?

![image](https://user-images.githubusercontent.com/3793636/111657733-b8063680-87d9-11eb-9773-dc8fd3f8cf92.png)

4. The horizontal rules are using two different colors. I don't think that's intended, right?

![image](https://user-images.githubusercontent.com/3793636/111657865-d704c880-87d9-11eb-90f5-c4c50e7067d0.png)

5. Looks like some spacing issues with the supporting items.

![image](https://user-images.githubusercontent.com/3793636/111658065-04ea0d00-87da-11eb-86b4-1f0555f9bb13.png)

6. Nitpicky thing, but is this a `media type`? The functional specs I call it a `supporting element`. I'm not necessarily saying we HAVE to use that here, but I don't think `media type` is accurate.

![image](https://user-images.githubusercontent.com/3793636/111658121-0fa4a200-87da-11eb-98cd-77be231280e5.png)

7. I think you have the video title and duration in the wrong place.

![image](https://user-images.githubusercontent.com/3793636/111658955-d28cdf80-87da-11eb-898e-9f295d4236e6.png)

8. Why does the type size change here? CTA block should be using expressive-heading-05 for the heading, and `heading-03` for that copy.

![image](https://user-images.githubusercontent.com/3793636/111659435-3ca58480-87db-11eb-8ab6-dc063904199d.png)

![image](https://user-images.githubusercontent.com/3793636/111659465-43cc9280-87db-11eb-9d02-8db877b6ac11.png)

2021-03-18 21:27 UTC, kirbyevans commented
Hey, @rastogir here are some issues I'm noticing in addition to @photodow 's notes from above.

1.Content section heading in the left column area should only span 3 columns
2. Main content area needs shifted left to align with the 16-column grid.
 
<img width="1314" alt="Pasted_Image_3_18_21__4_40_PM" src="https://user-images.githubusercontent.com/77290329/111695232-3e863c80-8809-11eb-81a7-9c83efaad7ad.png">

----

1. Appears to be some alignment issues with the Content item component. Additional space getting added to title on shorter Content items.
2. CTA text link with icon should consistently align based on longest content item character count. See design spec for more detail.
3. I want to also confirm that an additional CTA text link with icon can be added to a Content item for a max of two links if needed.

<img width="1272" alt="Pasted_Image_3_18_21__4_55_PM" src="https://user-images.githubusercontent.com/77290329/111698041-b99d2200-880c-11eb-8613-33704317d30e.png">

----

@photodow did we determine if this logic was in scope or not?

> **Minimum of two items per row**
> Avoid orphaned rows with one item. When this occurs the item in the third column from the row above should drop to the row below.

----

1. Bottom spacing for items in the last row should be 160px.

<img width="846" alt="Pasted_Image_3_18_21__5_21_PM" src="https://user-images.githubusercontent.com/77290329/111699625-c28ef300-880e-11eb-9aaa-b651455e32b7.png">

2021-03-19 14:21 UTC, photodow commented
> @photodow did we determine if this logic was in scope or not?

Out of scope. There should be a `# of column` prop so the AEM CMS can drop it if a given orphan is present. I didn't see a knob to test this, but I did see one story had 2 columns, and another story had 3 columns.

2021-03-19 22:22 UTC, rastogir commented
@asudoh 
- [ ]  Created sandbox example however I'll need to update it before PR is merged 
- [ ] Also added plain markup 

@photodow 
- [ ] CTA block, and CTA section are backwards. What you have as CTA block should be CTA section and vice versa. 
- [ ] Casing needs to be fixed. We use sentence casing for these

  - Meeting scheduled for 3/22 to discuss the requirement and implementation for above two feedbacks.

- [ ] Is CTA section missing bottom spacing?
- [ ] The horizontal rules are using two different colors. I don't think that's intended, right? _This is as per design spec_  
- [ ] Looks like some spacing issues with the supporting items.
- [ ] Nitpicky thing, but is this a media type? The functional specs I call it a supporting element. I'm not necessarily saying we HAVE to use that here, but I don't think media type is accurate.
- [ ] WIP - I think you have the video title and duration in the wrong place.
- [ ] Why does the type size change here? CTA block should be using expressive-heading-05 for the heading, and heading-03 for that copy.

@kirbyevans 

- [ ] Content section heading in the left column area should only span 3 columns

- [ ] Main content area needs shifted left to align with the 16-column grid.

- [ ] Appears to be some alignment issues with the Content item component. Additional space getting added to title on shorter Content items. @asudoh Any guidance on this?

- [ ] CTA text link with icon should consistently align based on longest content item character count. See design spec for more detail. @asudoh Any guidance on this?

- [ ] WIP - I want to also confirm that an additional CTA text link with icon can be added to a Content item for a max of two links if needed.

- [ ] WIP - Bottom spacing for items in the last row should be 160px.

2021-03-22 06:13 UTC, asudoh commented
> Appears to be some alignment issues with the Content item component. Additional space getting added to title on shorter Content items. @asudoh Any guidance on this?

Some quick findings are:

* We went away from using `bx--grid` for container `<div>s` in content pattern stories, including [one for CTA block](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/3cfee32aefc3015eeeacf74523c435b015b12433/packages/web-components/src/components/cta-block/__stories__/cta-block.stories.ts#L167). That should be replaced with `dds-ce-demo-devenv--simple-grid`.
* Along with `dds-ce-demo-devenv--simple-grid`, we define how much grid columns the story content takes. You can see it at [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/v1.16.1/packages/web-components/.storybook/container.scss#L77-L141). Seems that [one for CTA block uses `dds-ce-demo-devenv--simple-grid--content-layout`](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/3cfee32aefc3015eeeacf74523c435b015b12433/packages/web-components/src/components/cta-block/__stories__/cta-block.stories.ts#L167), which means [taking 5th to 12th grid columns in `lg` or larger breakpoints](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/v1.16.1/packages/web-components/.storybook/container.scss#L114-L118). Seems that we want the whole 1st to 16th columns for CTA block, and thus `dds-ce-demo-devenv--simple-grid--content-section` is more applicable.

One you apply above two changes (replacing `bx--grid` with `dds-ce-demo-devenv--simple-grid` as well as replacing `dds-ce-demo-devenv--simple-grid--content-layout` with `dds-ce-demo-devenv--simple-grid--content-section`), you'll see that `<dds-cta-block>` now aligns to the Carbon grid well. Now let's take a look at what's inside `<dds-cta-block>`:

* The grid columns inside `<dds-cta-block>` should be 25%/75% split. However, I see [a different split](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/3cfee32aefc3015eeeacf74523c435b015b12433/packages/styles/scss/components/cta-block/index.scss#L30) - I guess it's for getting some padding? If so, the padding should be applied by something else.
* The [`column-gap` applied in the grid](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/3cfee32aefc3015eeeacf74523c435b015b12433/packages/styles/scss/components/cta-block/index.scss#L27) seems to make the subgrid of `<div class="bx--content-section__children">` off from the parent grid. I recommend removing the gutter there and use different mean to add padding to the heading/copy/link above the cards.
* `<div class="bx--cta-block__items">` has [negative margin adjustment](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/3cfee32aefc3015eeeacf74523c435b015b12433/packages/styles/scss/components/cta-block/index.scss#L43-L44). It has adverse side effect and we are moving away from it. Removing such negative margin along with other fixes ensures correct grid alignment.

> CTA text link with icon should consistently align based on longest content item character count. See design spec for more detail. @asudoh Any guidance on this?

If it means the vertical position of the CTA text link, the best approach is ensuring that the CTA text link is placed at the bottom of `<dds-cta-block-item>`.

2021-03-23 22:50 UTC, rastogir commented
Thanks @asudoh for the detailed guidance! I cleaned up the classes and was able to achieve vertical position of the CTA text link in `<dds-cta-block-item>` via flex properties. Attached a screenshot. CTA block is going behind the feature flag because of some refactor work. Do I need to delete CodeSandBox example? 
![Screen Shot 2021-03-23 at 4 04 54 PM](https://user-images.githubusercontent.com/11525031/112223861-72da6e00-8bf8-11eb-8688-11eaca56c365.png)

@andysherman2121 @photodow @RaphaelAmadeu 

As discussed CTA block is behind the feature flag and CTA Section > Cta Block variant is removed. Below are CTA Section and CTA Block refactor details we discussed which can be used for the new ticket.

## CTA Section > Default variant will become CTA Block. 
![Screen Shot 2021-03-23 at 5 08 39 PM](https://user-images.githubusercontent.com/11525031/112225222-74a53100-8bfa-11eb-818b-70436541403b.png)

  - Under the hood CTA Block should utilize Content Block component
     - Use `<dds-content-block-heading>` for CTA Block heading. This is implemented correctly in CTA Section.
     - Use `<dds-content-block-paragraph>` or `<dds-content-block-copy>` for CTA Block copy. Currently `<dds-cta-section-item-copy>` is being used which extend `DDSContentItemCopy`. This will need to be corrected.
     - Currently Content Block component doesn't have a CTA. Functional requirement is to create one and use it for CTA Block CTA
     - This newly created Content Block CTA should also be used in other content block components such Content Block Cards, Content Block Mixed, Content Block Media, Content Block Segmented, Content Block Simple. Technical implementation for this refactor needs to be discussed.
     - CTA Block CTA should have a prop to switch between button group, text link and none.  
   - CTA Block will have below variants
   
![image (16)](https://user-images.githubusercontent.com/11525031/112225789-50961f80-8bfb-11eb-9859-8607aaa3febd.png)

    - Default
    
![Screen Shot 2021-03-23 at 5 08 39 PM](https://user-images.githubusercontent.com/11525031/112225622-0e6cde00-8bfb-11eb-9c55-6bfa7c408e3b.png)

    - With Content Items
    
![Screen Shot 2021-03-23 at 5 14 01 PM](https://user-images.githubusercontent.com/11525031/112225710-33f9e780-8bfb-11eb-9051-092799cae19f.png)

    - With Link List
    
![Screen Shot 2021-03-23 at 5 14 07 PM](https://user-images.githubusercontent.com/11525031/112225725-38be9b80-8bfb-11eb-9635-43fde1dbbcaa.png)

## CTA Block will become CTA Section.
  - CTA Section variants are
![image (16)](https://user-images.githubusercontent.com/11525031/112226111-bf737880-8bfb-11eb-832c-f397cca43bce.png)

<pre>- Default. This will utilize CTA Block > default under the hood. Users should be able to switch between button group, text links and none via a prop.</pre>
  
<img width="896" alt="Screen Shot 2021-03-23 at 5 21 46 PM" src="https://user-images.githubusercontent.com/11525031/112226540-44f72880-8bfc-11eb-908f-9bce0268e2b4.png">

    - With Content Items. Users should be able to switch image to video, pictogram, statistics and none via a prop. This is already at CTA Block > Default variant which is behind the feature flag. Design spec for this variant is at https://ibm.ent.box.com/s/shr0pnhof0yzk2b5lh0nokwopgxxb9rr
   
<img width="1073" alt="Screen Shot 2021-03-23 at 5 24 37 PM" src="https://user-images.githubusercontent.com/11525031/112226803-ac14dd00-8bfc-11eb-8be7-9bf861448efd.png">

    - With Link List. 
<img width="901" alt="Screen Shot 2021-03-23 at 5 30 47 PM" src="https://user-images.githubusercontent.com/11525031/112227359-876d3500-8bfd-11eb-8890-877200c1fba3.png">

Refactor work will also include below two feedbacks from this PR:

- Bottom spacing for items in the last row should be 160px from Kirby.
- I think you have the video title and duration in the wrong place from James.

2021-03-24 00:15 UTC, asudoh commented
>  CTA block is going behind the feature flag because of some refactor work. Do I need to delete CodeSandBox example?

@jeffchew What is our policy for CodeSandbox examples of roped-off components? Thanks!

2021-03-24 00:25 UTC, jeffchew commented
We can exclude if behind a feature flag, but my understanding is that this feature is going straight to production ready.

2021-03-24 01:31 UTC, shixiedesign commented
Hi Ravenna, thank you and this is a lot of work! My understanding is this is not a feature-flagged component, and should go into prod. But I noticed your comment:

> CTA block is going behind the feature flag because of some refactor work. Do I need to delete CodeSandBox example?

I suggest if this needs more work, we don't rush it by putting it behind feature flag. If the dev team has agreed to put it behind feature-flag, it would also require a different tag to ensure `experimental` environment gets build. So I cannot review it in the PR preview builds right now. Could you double check that feature flag decision with the dev team? Thank you!

2021-03-24 12:13 UTC, rastogir commented
@asudoh @jeffchew @shixiedesign Component is almost production ready. There is a requirement to rename existing CTA Section to CTA Block and address some technical debt which will require significant refactor work. Refactor work is detailed in my last comment. A seasoned DDS developer would be appropriate for the refactor job hence the reason why this component is put behind the feature flag. If needed there is an option to decrease the scope of refactor work. Happy to schedule a meeting to go over the technical details.

2021-03-24 19:14 UTC, rastogir commented
@shixiedesign Experimental preview is built and it's ready for your review https://ibmdotcom-web-components-experimental.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/5530/index.html?path=/story/components-cta-block--default

2021-03-29 19:25 UTC, jeffchew commented
Closing this PR, @RaphaelAmadeu will be opening a new one.

2021-03-29 19:25 UTC, closed without merging