Fix/masthead global styles
carbon-design-system/carbon-for-ibm-dotcom pull request #5716
Opened 2021-04-06 19:20 UTC by mherchel

### Related Ticket(s)

[HC-1679](https://jsw.ibm.com/browse/HC-1679)

### Description

{{Add a human-readable description / detail summary of what the PR is changing and any details around how and why}}

{{If applicable, include a screenshot indicating an example or examples of what the PR is changing in the application}}

### Changelog

**New**

- {{new thing}}

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

2021-04-06 19:42 UTC, mherchel commented
Note that I didn't make any changes to the chevron down icon within the desktop navigation. This icon is imported through a different package (see https://github.com/carbon-design-system/carbon-web-components/blob/master/src/components/ui-shell/header-menu.ts#L13). 

However, the icons are 10x6, so they shouldn't require any changes.

2021-04-15 17:13 UTC, proeung commented
@mherchel Thanks for fixing up the CI issues. I think this PR is ready for code and design QA, so please change the status of this PR from a draft to publish.

> "Log in" text for logged out state of the menu (no drop down in logged out state)
>  User icon for account drop down once logged in (menu items will vary between IBM.com and Cloud)

Also, the two items that you've listed above have already been accounted for in @huntermacd's [PR ](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5593)that got merged as an experimental feature flag.

2021-04-16 14:53 UTC, shixiedesign requested changes
1. I'm seeing all the links in the library are impacted by this PR and that should not happen. 

![image](https://user-images.githubusercontent.com/15144993/115042504-8c8e6e80-9ea1-11eb-9481-d25f53986e57.png)

2. Corporate masthead should not be affected. 

![image](https://user-images.githubusercontent.com/15144993/115042826-d5debe00-9ea1-11eb-837e-0eefc9ee670e.png)


![image](https://user-images.githubusercontent.com/15144993/115042699-be073a00-9ea1-11eb-8ac9-5cc6f4d3afcb.png)

2021-04-16 14:58 UTC, annawen1 commented on packages/styles/scss/themes/expressive/_tokens.scss
> +    font-size: carbon--type-scale(2),
Don't think we should be changing the font size here as it will affect every component using these tokens.

2021-04-16 15:03 UTC, annawen1 commented on packages/styles/scss/themes/expressive/_tokens.scss
> +    font-size: carbon--type-scale(2),
If we have to use `body-short-01` but we want 14px instead of 16px - there is a `@include use-carbon-productive-tokens();` mixin that we use.

2021-04-23 18:26 UTC, shixiedesign commented
Had a quick chat with @proeung and I understood how this happened. So FYI @mherchel the current `body-short` maps to 16px is correct because in dotcom we utilize an expressive theme that bumps up original Carbon token values ([see explanation here](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/guidelines/expressive-theme)) . We need to keep that unchanged for now so the rest of Dotcom is unaffected. 

Please ping whenever the changes are in place. Thank you!

2021-04-27 18:47 UTC, proeung commented
I think we can close out this PR. I'm going to create a new one that we're using for the overall design QA of the Cloud masthead work.

2021-04-27 18:48 UTC, annawen1 commented
Closing this PR as @proeung will be opening another one

2021-04-27 18:48 UTC, closed without merging