feat(cloud-masthead): adjust "Contact us" button visibility
carbon-design-system/carbon-for-ibm-dotcom pull request #5874
Opened 2021-04-22 18:38 UTC by huntermacd

### Related Ticket(s)

https://jsw.ibm.com/browse/HC-1810

### Description

This diff adds a new attribute to the cloud-masthead-composite component that controls the visibility of the Contact us button. Additionally, updated the Storybook story to include a toggle so this can be seen in action.

![image](https://user-images.githubusercontent.com/4371669/115768395-7da73080-a367-11eb-82a1-0655211d6d18.png)

![Screen Shot 2021-04-22 at 2 32 12 PM](https://user-images.githubusercontent.com/4371669/115768423-85ff6b80-a367-11eb-9cda-dc1b00a1c05f.png)

### Changelog

**New**

- n/a

**Changed**

- cloud-masthead-composite.ts
- cloud-masthead.stories.ts

**Removed**

- n/a

2021-04-23 18:05 UTC, shixiedesign commented
Had a discussion with @proeung and I understand what this PR does now. Good to go through our regular code review process and no need for design review. Thanks!

2021-04-26 14:35 UTC, proeung commented on packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts
> +                      <dds-cloud-button-cta kind="ghost">${contactUsButton?.title}</dds-cloud-button-cta>
We'll need to account for the `data-ibm-contact=` attribute to trigger the "Let's Chat" contact module. Here's the link to the doc that Jeff shared with us - https://www.ibm.com/standards/web/v19a-archive/components/contact-module/#call-to-actions

2021-04-26 14:37 UTC, proeung requested changes
@huntermacd Looks good overall! Thanks for adding the knob for changing the visibility of the "Contact us" button. 

I think the one thing that we're missing is the ability to set this button in a way that triggers the "Let's Talk" contact module on pages where it's being used.

2021-04-26 20:08 UTC, proeung approved these changes

2021-04-26 21:44 UTC, proeung commented
@huntermacd Thanks for addressing my feedback and let's make sure the branch is up to date with the base branch.

@annawen1 This PR is ready for a code review.

2021-04-27 13:20 UTC, annawen1 approved these changes
LGTM! Thanks @huntermacd

2021-04-27 13:35 UTC, ariellalgilmore reviewed
Looks good! I noticed though this is only for desktop and just wanted to confirm that this is intended.

2021-04-27 17:04 UTC, ltitle commented
I think we discussed removing Contact us on mobile due to screen real estate and because the lets talk icon will be in close proximity.

2021-04-27 17:11 UTC, proeung commented
@ltitle Thanks for the confirmation! I think this PR is good for merging then!

2021-04-27 17:24 UTC, merged