Fix/link list section items
carbon-design-system/carbon-for-ibm-dotcom pull request #6910
Opened 2021-08-17 20:53 UTC by andy-blum

### Related Ticket(s)

Fixes #6830 

### Description

- Sets `link-list-item` elements within `link-list__list--split` and `link-list__list--three-columns` to `display:grid`
- Updates `link-list-section` storybook config to have one item with a very long title.

<img width="1148" alt="Screen Shot 2021-08-17 at 4 51 14 PM" src="https://user-images.githubusercontent.com/25532785/129798803-ca122772-92cf-4f3c-9846-87b69f8ac8f8.png">

### Changelog

**Changed**

- web component link-list items in 2 & 3 column layouts display as grid & center-align their contents
- web component link-list-section has one item with very long title text

2021-08-17 21:39 UTC, IgnacioBecerra commented
@andy-blum Thanks for opening this PR, looks great with the fix! 

Looks like you just have to run `yarn format` so the ci-check can pass 👍

2021-08-18 12:55 UTC, shixiedesign requested changes
Hi! Thanks for opening a fix, though this is not the correct design. The expected result is still top aligned link texts. The current bug (please [see Anna's comment to clarify](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6830#issuecomment-897640939)) is with hover's background color change. Both icon and link text should be 16px from the top rule, not centered: 

![image](https://user-images.githubusercontent.com/15144993/129901650-c2815516-089d-4d9d-aaac-11c532aaa10d.png)

![image](https://user-images.githubusercontent.com/15144993/129901505-0b89bd54-243e-4b33-99f0-6bc71d64fabf.png)

2021-08-18 17:41 UTC, shixiedesign commented
A little more detailed spec: 
![image](https://user-images.githubusercontent.com/15144993/129946113-d6052702-c7c0-4d8a-ad81-26642c5d546b.png)

2021-08-19 11:50 UTC, shixiedesign commented
@andy-blum Whenever you are ready for another look, please remove `⚒️ fix needed` label, and add the label `👀 eyes needed`. Thanks!

2021-08-19 14:42 UTC, shixiedesign commented
Thank you! @andy-blum Much better and really close - only 1 comment, the spacing between text and arrow icon should be 32px. 

**Currently 8px:**
![image](https://user-images.githubusercontent.com/15144993/130088704-c36ff91f-cd9d-4a83-b204-a4d49e33765c.png)

**Expecting 32px** 
![image](https://user-images.githubusercontent.com/15144993/130089055-b786de67-4f76-4b78-b920-ad2bfc5cc41c.png)

2021-08-19 19:04 UTC, andy-blum commented
@shixiedesign I just updated the icon's padding value, but I'm hesitant to update the styles for the link-list default view as the center-alignment there comes from dds-card-footer

<img width="855" alt="Screen Shot 2021-08-19 at 2 47 00 PM" src="https://user-images.githubusercontent.com/25532785/130129125-32733f44-2366-4cae-9e34-b4c6fe745737.png">

2021-08-20 12:09 UTC, shixiedesign commented
@andy-blum Hmm thanks for checking! I just looked at our Cards, and seems like the link text simply doesn't wrap 😱 I just filed [a bug issue for this](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/6935). But I'm gonna check with our dev to see what's the usual approach when this happens. More soon.

2021-08-20 14:23 UTC, kennylam commented
@shixiedesign This icon alignment should be consistent for `card` and all components which use it, correct? If so then changing `dds-card-footer` should be fine @andy-blum.

2021-08-20 18:20 UTC, andy-blum commented
@shixiedesign pinging you since I can't update labels - this should be ready for your re-review

2021-08-23 12:53 UTC, shixiedesign commented
Almost there! Only noticed in Link list - default, at `sm` breakpoint, missing 32px spacer between arrow and wrapping text 
![image](https://user-images.githubusercontent.com/15144993/130450397-434e6bd0-8dc5-48af-82bd-cf2c1f82da40.png)

2021-08-23 18:19 UTC, andy-blum commented
@shixiedesign 👀 eyes needed

2021-08-23 19:13 UTC, shixiedesign commented
@andy-blum Hey looks like you didn't contain the change to only mobile? Desktop of Link list - default looks off now: 
![image](https://user-images.githubusercontent.com/15144993/130504364-3cf8f5b8-b110-4614-849d-0c5535baa321.png)

2021-08-24 14:15 UTC, shixiedesign approved these changes
Perfect. Thank you! 👍

2021-08-24 14:17 UTC, andy-blum commented
Forgot to run `yarn format` for CI checks.

2021-08-24 14:38 UTC, shixiedesign commented
Hey @andy-blum if you still have a second, can we shorten the link text in Link list section to `Learn more about Kubernetes and automating deployment `. It's still gonna wrap so good for future testing. Thanks!

2021-08-24 14:45 UTC, emyarod reviewed
looks good to me, just one note about the storybook example

2021-08-24 14:45 UTC, emyarod commented on packages/web-components/src/components/link-list-section/__stories__/link-list-section.stories.ts
> +          applications. ${ArrowRight20({ slot: 'icon' })}
I think we can shorten this to `Learn more about Kubernetes and automating deployment`

2021-08-24 14:50 UTC, jeffchew commented
Hi @andy-blum ! Can you check on the following stylelint issue?

![image](https://user-images.githubusercontent.com/1641214/130638751-9e5e8a1f-8f13-43b2-9244-cd65efdc689f.png)

2021-08-24 15:38 UTC, jeffchew approved these changes
LGTM!

2021-08-24 15:39 UTC, merged