test(card-section-images): add e2e tests
carbon-design-system/carbon-for-ibm-dotcom pull request #7771
Opened 2021-11-29 18:32 UTC by BrunnoM7

### Related Ticket(s)

[Test Scenario]: Card-section-images #7447

### Description

Created e2e test cases for the `card-section-images` component covering the scenarios:
- Check cards with images, content is loaded and whole card clickable
- Check heading (bold) left aligned.
- Check the content (Eyebrow, heading, copy and arrow link) is loading on the card
- Customize theme from Carbon theme and verify gray 10, gray 90 and gray 100 theme.

### Changelog

**New**

- e2e test cases for `card-section-images` in both react and web components

2021-11-29 21:09 UTC, jeffchew commented on packages/react/tests/e2e-storybook/cypress/integration/CardSectionImages/CardSectionImages.e2e.js
> +      }
Replace with `cy.takeSnapshots()`

2021-11-29 21:10 UTC, jeffchew commented on packages/react/tests/e2e-storybook/cypress/integration/CardSectionImages/CardSectionImages.e2e.js
> +  it('should load the g10 theme', () => {
Replace all of the theme tests with:

```
cy.carbonThemesScreenshot(
      {},
      {
        widths: [320],
      }
    );
```

2021-11-29 21:10 UTC, jeffchew commented on packages/react/tests/e2e-storybook/cypress/integration/CardSectionImages/CardSectionImages.e2e.js
> +  it('should load the g10 theme', () => {
cy.carbonThemesScreenshot(
      {},
      {
        widths: [320],
      }
    );

2021-11-29 21:11 UTC, jeffchew commented on packages/react/tests/e2e-storybook/cypress/integration/CardSectionImages/CardSectionImages.e2e.js
> +    );
Replace with `cy.takeSnapshots('mobile')`

2021-11-29 21:11 UTC, jeffchew commented on packages/web-components/tests/e2e-storybook/cypress/integration/card-section-images/card-section-images.e2e.js
> +    });
Replace with `cy.takeSnapshots()`

2021-11-29 21:12 UTC, jeffchew commented on packages/web-components/tests/e2e-storybook/cypress/integration/card-section-images/card-section-images.e2e.js
> +  it('should load the g10 theme', () => {
Replace all of the theme tests with:

```
it('should load correctly in all themes', () => {
    cy.visit(`/${_pathDefault}`);
    cy.viewport(1280, 780);

    cy.carbonThemesScreenshot();
  });
```

2021-11-29 21:14 UTC, jeffchew commented on packages/web-components/tests/e2e-storybook/cypress/integration/card-section-images/card-section-images.e2e.js
> +    });
Replace with `cy.takeSnapshots('mobile')`

2021-11-29 21:15 UTC, jeffchew commented on packages/web-components/tests/e2e-storybook/cypress/integration/card-section-images/card-section-images.e2e.js
> +  it('should load the g10 theme', () => {
Replace all of the theme tests with:

```
it('should load correctly in all themes', () => {
    cy.visit(`/${_pathDefault}`);
    cy.viewport(320, 780);

   cy.carbonThemesScreenshot(
      {},
      {
        widths: [320],
      }
    );

  });
```

2021-11-29 21:22 UTC, jeffchew requested changes
Hey @BrunnoM7 see my comments, similar to the other e2e test PR, a lot of the Percy snapshot lines can be replaced with the global methods now.

2021-11-30 15:05 UTC, BrunnoM7 commented
Thanks for reviewing @jeffchew. I just applied the changes you mention.

2021-11-30 22:30 UTC, jeffchew approved these changes
Thank you for making the changes!

2021-12-01 01:06 UTC, merged