fix(feature-card): make entire card clickable on mobile viewports
carbon-design-system/carbon-for-ibm-dotcom pull request #7853
Opened 2021-12-10 15:54 UTC by andy-blum

### Related Ticket(s)

Fixes #7806

### Description

This PR removes unnecessary declarations of `position:relative;` causing the link's `:after` pseudo-element (indicated by red region in below images) to only cover the card's content area but not the image area.

Before:
<img width="521" alt="Screen Shot 2021-12-10 at 10 53 40 AM" src="https://user-images.githubusercontent.com/25532785/145602679-af3e51fe-8028-4cd0-bfa6-6c21275a2c64.png">

After:
<img width="521" alt="Screen Shot 2021-12-10 at 10 53 15 AM" src="https://user-images.githubusercontent.com/25532785/145602713-c50fcdd5-eec1-4240-862a-f28b3fe7ae71.png">

### Changelog

**Changed**

- Makes entirety of feature-card component clickable on mobile

2021-12-10 19:05 UTC, proeung requested changes
I'm seeing a regression in the mobile breakpoints where the CTA hover stylings are not coming through (see screenshot). Hover should be consistent on all breakpoints.


https://user-images.githubusercontent.com/1815714/145628030-29203ed0-f275-489b-8058-8134a5b32b22.mov

@shixiedesign or @RichKummer Can you help take a look as well? Thanks!

2021-12-10 20:25 UTC, andy-blum commented
@proeung What hover state are you comparing this to? The deploy preview and canary match up perfectly for me (brower tabs change at 0:06 below)

https://user-images.githubusercontent.com/25532785/145636930-9a433f3f-5352-4307-8574-ab25275a5c64.mov

2021-12-14 18:36 UTC, proeung commented
@andy-blum Looks like the mobile hover state regression that I noted above is happening on the [WC canary preview](https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-cta--feature) as well, which means that it's not a regression coming from this particular PR. If we can, let's figure out what's causing this issue and push up a solution in this PR.

Card hover state should be `var(--cds-inverse-hover-ui, #4c4c4c)`.

cc: @IgnacioBecerra @oliviaflory @RichKummer

2021-12-16 20:54 UTC, emyarod approved these changes
looks good to me!

2021-12-17 17:39 UTC, proeung commented on packages/styles/scss/components/feature-card/_feature-card.scss
> +      .bx--card__wrapper {
Minor nitpicking, but let's use the `$prefix` variable.

```suggestion
      .#{$prefix}--card__wrapper {
```

2021-12-17 17:42 UTC, proeung commented
Looks good overall! Thanks for fixing the hover state issue seen the mobile breakpoints. I just have one minor feedback and I think this PR should be good for merging unless we need further QA from the design team.

2021-12-20 15:57 UTC, proeung approved these changes

2021-12-22 15:21 UTC, annawen1 commented
@andy-blum Percy caught this happening in the `Back to Top` story where the feature card is being used in 320px screen size where the icon is going out of the card. Is that a quick fix?

<img width="413" alt="Screen Shot 2021-12-22 at 10 19 13 AM" src="https://user-images.githubusercontent.com/54281166/147114957-d86ab1b9-d559-4528-bd77-4502c1e7bf27.png">

2021-12-22 19:26 UTC, andy-blum commented
While we could refactor the card styles to make this adapt to fit that text, content guidance for this component directs a maximum of 65 characters and this implementation has 90 characters.

2021-12-22 19:44 UTC, annawen1 approved these changes
LGTM! Thanks @andy-blum!

2021-12-22 20:35 UTC, merged