fix(tabs-extended): change anchor-based tabs to button-based tabs
carbon-design-system/carbon-for-ibm-dotcom pull request #8365
Opened 2022-02-23 20:39 UTC by andy-blum

### Related Ticket(s)

Fixes #8357 

### Description

Fixes an issue where iOS on tablet couldn't use tabs.

### Changelog

**Changed**

- changes `<a>` elements to `<button>` elements in tabs so iOS devices getting the desktop-style layout can navigate with voiceover

2022-02-24 22:09 UTC, RichKummer commented
Hey @andy-blum , I tested this on iOS and I'm seeing that we're able to navigate between tabs with VoiceOver on. I noticed that when a tab is focused and if the tab has a tooltip, he focus area includes the tooltip even if the tab is not active yet. Is this the expected behavior for tabs with tooltips?

While Tab 1 is active but with Tab 2 selected, you can see the focus dips below the tab itself
![IMG_1192](https://user-images.githubusercontent.com/15643582/155614796-bb39b65d-7022-4ede-a8d5-19dedbb0e8d8.jpg)

Here Tab 2 is active and you can see that the focus is capturing the tooltip
![IMG_1193](https://user-images.githubusercontent.com/15643582/155615175-7dc12e5c-9e83-4cdc-978d-9450709f16c9.jpg)

2022-03-02 13:59 UTC, kennylam reviewed
Thanks @andy-blum! Just a few small things.

2022-03-02 13:59 UTC, kennylam commented on packages/styles/scss/components/tabs-extended/_tabs-extended.scss
> +  line-height: 1rem;
Can use token here.

2022-03-02 13:59 UTC, kennylam commented on packages/styles/scss/components/tabs-extended/_tabs-extended.scss
> +    padding-left: 16px;
Can use token here.

2022-03-02 13:59 UTC, kennylam commented on packages/styles/scss/components/tabs-extended/_tabs-extended.scss
> +        width: 10rem;
```suggestion
        width: rem(160px);
```

2022-03-02 20:45 UTC, kennylam commented on packages/styles/scss/components/tabs-extended/_tabs-extended.scss
> +  line-height: 1rem;
https://www.carbondesignsystem.com/guidelines/spacing/overview/

2022-03-03 18:37 UTC, RichKummer commented
Hey @andy-blum , I'll wait to re-review until Kenny's suggested changes are in, but I checked again on tablet with VO and it looks like the change to the tab selection was resolved - yay! 

I'll keep an eye out for the other changes and then run through it again then

2022-03-04 21:16 UTC, RichKummer approved these changes
Looks great @andy-blum , thanks for making the change!

2022-03-07 22:55 UTC, proeung requested changes
Looks good overall! I just have a few suggestions related to keeping with using carbon tokens for color and spacings.

2022-03-07 22:55 UTC, proeung commented on packages/styles/scss/components/tabs-extended/_tabs-extended.scss
> +        border-bottom: 2px solid var(--cds-ui-03, #e0e0e0);
```suggestion
        border-bottom: carbon--rem(2px) solid $ui-03;
```

2022-03-07 22:55 UTC, proeung commented on packages/styles/scss/components/tabs-extended/_tabs-extended.scss
> +  width: calc(100% - 32px);
```suggestion
  width: calc(100% - #{$spacing-07});
```

2022-03-07 22:55 UTC, proeung commented on packages/styles/scss/components/tabs-extended/_tabs-extended.scss
> +      border-bottom: 2px;
```suggestion
      border-bottom: carbon--rem(2px);
```

2022-03-08 17:37 UTC, mwanberg commented
I think this will need to be merged before I can finish my related PR: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8394

2022-03-08 21:24 UTC, proeung approved these changes
LGTM! Thanks for applying my suggestions!

2022-03-08 21:24 UTC, merged