Feat/masthead 2.1 mobile
carbon-design-system/carbon-for-ibm-dotcom pull request #9929
Opened 2023-01-20 20:43 UTC by andy-blum

### Related Ticket(s)

[ADCMS-2612](https://jsw.ibm.com/browse/ADCMS-2612)

Followup to #9829 

### Description

Updates masthead left-nav to use new masthead v2.1 styles & data structure

### Changelog

**Changed**

- Updates to style of left-nav and sub-components

2023-01-24 21:14 UTC, jkaeser commented
@andy-blum I've been keeping this initiative's work isolated in `feat/masthead-v2.1`. Can you merge it into this branch and set it as the PR's target branch?

If you find that level of isolation unnecessary, we can instead merge `feat/masthead-v2.1` into `feat/masthead-v2-dev`, then merge `feat/masthead-v2-dev` back into this branch again.

2023-01-25 17:50 UTC, jkaeser requested changes
@andy-blum Looking good so far!

## Code Notes
1. We need to make sure the "selected" nav items still work. This is the mechanism that applies a special style to links that match the current page URL.

## Design Notes
1. It looks like the link text is still using `body-short-02`, but it should use `body-short-01`.
   <img width="1675" alt="Screen Shot 2023-01-25 at 12 17 46 PM" src="https://user-images.githubusercontent.com/12532727/214637053-c2deb537-bda4-41e4-a1c6-749e64827195.png">
2. There's extra space beneath some headings. Pretty sure this is unwanted.
   - <img width="1675" alt="Screen Shot 2023-01-25 at 12 18 19 PM" src="https://user-images.githubusercontent.com/12532727/214637316-9b29b6c9-d29b-42f2-9384-73e353b8eb51.png">
   - <img width="701" alt="Screen Shot 2023-01-25 at 12 24 27 PM" src="https://user-images.githubusercontent.com/12532727/214637726-9b4fccf8-4389-4380-93f1-bfa11e03a1a2.png">
3. The "view all" CTAs should be blue and have an arrow. Or are you waiting for the specific ticket that handles view all (which would be fine, just want to check)?
   <img width="701" alt="Screen Shot 2023-01-25 at 12 22 39 PM" src="https://user-images.githubusercontent.com/12532727/214637500-e9da0f5d-8971-4154-a8f5-f75821e7bcf3.png">

2023-01-25 17:50 UTC, jkaeser commented on packages/web-components/src/components/masthead/left-nav-menu-section.ts
> +// import ArrowRight20 from 'carbon-web-components/es/icons/arrow--right/20.js';
Nit: remove commented code

2023-01-25 17:50 UTC, jkaeser commented on packages/web-components/src/components/masthead/masthead-composite.ts
> +      if (elem.isHeading) {
Do we need this check, or can we add `.isHeading="${elem.isHeading}"` to the returned template fragment that follows this conditional instead?

2023-02-03 21:07 UTC, oliviaflory commented
Will leave a few comments to help start some design QA cc @jwitkowski79 – would love your eyes too!

## 1 Title not vertically centered
Echoing John's observation in item 2: the menu title is not vertically centered. See `Faceted megamenu`, `Simple megamenu` as examples.
<img width="465" alt="Screenshot 2023-02-03 at 3 34 49 PM" src="https://user-images.githubusercontent.com/45692622/216706387-ba54bc7a-b322-45ff-a1df-c57ebb24bedd.png">

**Expecting** to be vertically centered in a 48px container (Example "Products)
![Screenshot 2023-02-03 at 3 40 19 PM](https://user-images.githubusercontent.com/45692622/216706494-55aa89d4-5661-4721-92a7-31731e4e5359.png)

## 2 No change
The extra space below the Heading 1 is correct, no changes needed 👍 
<img width="509" alt="Screenshot 2023-02-03 at 3 44 09 PM" src="https://user-images.githubusercontent.com/45692622/216707248-cbdaee1f-78ea-4224-bd01-feb835dcd687.png">

## 3 Focus state for titles
Focus state for menu title might be coming from the system/browser default? 
<img width="444" alt="Screenshot 2023-02-03 at 3 46 41 PM" src="https://user-images.githubusercontent.com/45692622/216707885-ed97c6d9-d51d-490e-bcb0-55a090595c28.png">


**Expecting** state to match desktop, see [Figma spec sheet](https://www.figma.com/file/35JfN0Sg4ltIIjM7jBDKMk/Navigation?node-id=3188%3A178305&t=HfLw8W7bSB8d2Rdy-1)
![Screenshot 2023-02-03 at 3 48 08 PM](https://user-images.githubusercontent.com/45692622/216707927-d306c3a4-5052-419b-8200-efc544ef1443.png)

## 4 Title has extra vertical space (check with Jen)
Looks like the description might be holding extra space in the Heading 1? If no description is present I would have expected the container to be the line height of the heading size.
See `Faceted megamenu` / `No heading descriptions` as an example
<img width="439" alt="Screenshot 2023-02-03 at 3 52 14 PM" src="https://user-images.githubusercontent.com/45692622/216708875-05814006-0d37-4d68-b3c9-f6802bc213c1.png">

<img width="437" alt="Screenshot 2023-02-03 at 3 51 48 PM" src="https://user-images.githubusercontent.com/45692622/216708620-a5f16c31-4956-47a4-b38b-2aa8707a3ad2.png">

## 5 Type styles
Echoing John's comment that the following items should be using `body-short-01` paired with a 16x16 px icon 
- back button
- menu title
- link item
<img width="481" alt="Screenshot 2023-02-03 at 3 57 24 PM" src="https://user-images.githubusercontent.com/45692622/216709682-ea7c51a4-1484-4bdd-8935-76784fbd73e6.png">
<img width="466" alt="Screenshot 2023-02-03 at 3 57 34 PM" src="https://user-images.githubusercontent.com/45692622/216709686-ac07f7f0-db9f-4602-b53c-745637b89508.png">

2023-02-06 18:59 UTC, jwitkowski79 requested changes
@andy-blum Hello! A few other things not mentioned by @oliviaflory and @jkaeser.

### 1 Arrow alignment on clickable heading level 2
Currently the arrows are left aligned to the text. 
![27BEB7A2-EC87-4470-9FA6-B98965EDE8C4](https://user-images.githubusercontent.com/2040791/217058247-f5f17e3e-ebde-4cc6-9894-4d69b15bdf50.png)



**Expecting** that they should be right aligned as seen in the Figma file [here ](https://www.figma.com/file/35JfN0Sg4ltIIjM7jBDKMk/Navigation?node-id=4415%3A202956&t=GNmMs67BSPb7kCl0-1) and in the below screenshot

<img width="417" alt="5E27C5F1-694C-4B95-9E1D-2C843069F5C9" src="https://user-images.githubusercontent.com/2040791/217055327-42b94d9f-b0b8-4019-889d-bae18baa77cf.png">


### 2 Title has extra vertical space
@oliviaflory is correct in stating that the heading level 1 title is holding extra vertical space if the description is not included. If no description is being used, the space should collapse and only the title spacing + line-height should be visible.

2023-02-07 21:50 UTC, jkaeser requested changes
@andy-blum This is looking great! Almost there. Some dev changes got committed, and group headers should be type productive `heading-01`:

<img width="701" alt="Screen Shot 2023-02-07 at 4 48 09 PM" src="https://user-images.githubusercontent.com/12532727/217374668-bb6e29cb-c0e4-41ae-9c9b-fd78eae5a650.png">

2023-02-07 21:50 UTC, jkaeser commented on packages/web-components/src/components/masthead/masthead.scss
> +@import '../../../../styles/scss/components/masthead/masthead-leftnav';
Oops!

2023-02-07 21:50 UTC, jkaeser commented on packages/web-components/src/components/masthead/masthead-composite.ts
> +          .isHeading=${elem.isHeading ?? false}
👏

2023-02-09 15:02 UTC, jkaeser approved these changes

2023-02-10 18:42 UTC, proeung commented
@andy-blum - @jkaeser and I had a chance to chat today and we decided that it's best to merge these changes down so that we have all of the latest code in the `masthead-v2.1` branch. We can then create a deploy preview that both @oliviaflory and @jwitkowski79 can use to conduct a comprehensive design QA of the Masthead v2.1 updates.

2023-02-10 18:42 UTC, merged