chore(platform): add indexing file for `carbon-web-components`
carbon-design-system/carbon-for-ibm-dotcom pull request #9960
Opened 2023-01-27 15:57 UTC by kennylam

### Description

Index the `carbon-web-components` package with Carbon Platform.

@francinelucca For `externalDocsUrl` and `usage`/`style`/`a11y` paths, I've kept the links pointing to Carbon React documentation. Since `carbon-web-components` should (eventually) mirror the React components, I think it's a good idea to treat those as the canonical docs? Let me know what you think. Also please let me know if there is anything missing, for instance icons. Not sure where those should be added and if we even have one we should be using.

### Changelog

**New**

- `carbon.yml` index file for `carbon-web-components` package

2023-01-27 16:25 UTC, francinelucca commented
@kennylam pointing to `carbondesignsystem.com`'s documentation sounds good to me!

P.S.: since you're inheriting `carbon-styles` and `docs` is an inheritable property (see [platform's schema](https://next.carbondesignsystem.com/contributing/schema#asset-keys)) , you can forego writing the docs explicitly here and it will be passed down automatically as long as the asset ids match what's defined in https://github.com/carbon-design-system/carbon/blob/main/packages/styles/carbon.yml (this is not true for `externalDocsUrl` since that is not an inheritable property) 

Also if the components look more or less the same feel free to borrow some thumbs from [core](https://github.com/carbon-design-system/carbon/tree/main/packages/styles/thumbnails) and add the corresponding `thumbnailPath`

2023-01-27 16:34 UTC, francinelucca requested changes
Looking good! 🚀, some minor suggestions

2023-01-27 16:34 UTC, francinelucca commented on packages/carbon-web-components/carbon.yml
> +  description: Build user interfaces with web components based on Carbon's React library.
```suggestion
  description: Build user interfaces with web components based on Carbon's React library.
```

2023-01-27 16:34 UTC, francinelucca commented on packages/carbon-web-components/carbon.yml
> +  content-switcher:
```suggestion
  combo-box:
    status: stable
    framework: web-component
    demoLinks:
      - type: storybook
        name: Storybook
        action: link
        url: https://www.ibm.com/standards/carbon/carbon-web-components/?path=/docs/components-combo-box
  content-switcher:
```

2023-01-27 16:34 UTC, francinelucca commented on packages/carbon-web-components/carbon.yml
> +  data-table:
```suggestion
  copy-button:
    status: stable
    framework: web-component
    demoLinks:
      - type: storybook
        name: Storybook
        action: link
        url: https://www.ibm.com/standards/carbon/carbon-web-components/?path=/docs/components-copy-button
  data-table:
```

2023-01-27 16:34 UTC, francinelucca commented on packages/carbon-web-components/carbon.yml
> +  inline-loading:
```suggestion
  icon:
    name: Icon
    framework: web-component
    status: stable
    type: component
    demoLinks:
      - type: storybook
        name: Storybook
        action: link
        url: https://www.ibm.com/standards/carbon/carbon-web-components/?path=/docs/components-icon
    tags:
      - input-control
      - media
  inline-loading:
```

2023-01-27 16:34 UTC, francinelucca commented on packages/carbon-web-components/carbon.yml
> +    docs:
```suggestion
  multiselect:
    status: stable
    externalDocsUrl: https://www.carbondesignsystem.com/components/dropdown/usage/#multiselect
    framework: web-component
    demoLinks:
      - type: storybook
        name: Storybook
        action: link
        url: https://www.ibm.com/standards/carbon/carbon-web-components/?path=/docs/components-multi-select
```

2023-01-27 16:34 UTC, francinelucca commented on packages/carbon-web-components/carbon.yml
> +    docs:
```suggestion
  notifications:
    status: stable
    externalDocsUrl: https://www.carbondesignsystem.com/components/notification/usage
    framework: web-component
    demoLinks:
      - type: storybook
        name: Storybook
        action: link
        url: https://www.ibm.com/standards/carbon/carbon-web-components/?path=/docs/components-notifications
```

2023-01-27 16:45 UTC, kennylam commented
@francinelucca got it, thanks!

2023-02-01 19:24 UTC, francinelucca approved these changes
🚀

2023-02-02 16:39 UTC, ariellalgilmore approved these changes

2023-02-02 22:52 UTC, merged